### DISCUSSION TITLE
Python os.path.exists <=> Blobfuse2 interaction

### DISCUSSION THREAD

**Discussion by FrsECM** [Azure/azure-storage-fuse#1054] [Q&A] [answered]
Hi !
I've mounted a storage with blobfuse2 in an azureml compute instance :
It worked well and i can tree my structure :
![image](https://user-images.githubusercontent.com/26071804/217508485-2cb5125f-959a-4ac9-b59b-d214e356cb2b.png)

The problem is that when i perform a "os.path.exists()" in python, it fails because the file is not already cached.
![image](https://user-images.githubusercontent.com/26071804/217509111-686e584c-fc86-4560-ae9a-ca4584c43081.png)

I'm sure that it is existing :
![image](https://user-images.githubusercontent.com/26071804/217509330-13c0bda5-677d-460c-9f20-9b021570c1a0.png)

The weard things is that when i restart the job, it seems to be working after more trials....
If i list the directory containing my file and then open the file it work also.
In my configuration it's a blob storage that cause problem.

**Do you know if there is a parameter missing in my config in order fuse to "discover" the file structure before using it ?**

Here is my yaml file :
```yaml
# Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /tmp/.cache
  timeout-sec: 120
  max-size-mb: 512

attr_cache:
  timeout-sec: 600

azstorage:
  type: block
  account-name: <StorageName>
  endpoint: https://<StorageName>.blob.core.windows.net
  mode: sas
  sas: <SAS Token>


mountall:
  # allowlist takes precedence over denylist in case of conflicts
  container-allowlist:
    - celeba-hq-data
```

Thanks a lot for your help !
