### DISCUSSION TITLE
what is the oauth-token-path used for?

### DISCUSSION THREAD

**Discussion by casimir-dus** [Azure/azure-storage-fuse#1336] [Q&A] [answered]
Hey,

so I'm trying to configure blobfuse2 to use a service principal instead of SAS, in order to stay within msfts best practices regarding IAM in storage accounts.

The [base config](https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml) gives following parameters for SPN:
```yaml
  tenantid: <storage account tenant id for SPN>
  clientid: <storage account client id for SPN>
  clientsecret: <storage account client secret for SPN>
  oauth-token-path: <path to file containing the OAuth token>
```

Why and for what is a file needed for the OAuth token? 
I did not find anyone who configured this parameter, and don't know what to put there.

I got my tenant id, my client id and my client secret.
[This post](https://github.com/Azure/azure-storage-fuse/discussions/1153) also specified `auth-resource`.
This param is also listed in the [environment variable documentation](https://github.com/Azure/azure-storage-fuse/tree/main?tab=readme-ov-file#environment-variables).

Can anyone provide some guidance on how to setup Blobfuse2 with Service Principals?
