### DISCUSSION TITLE
How to use blobfuse2 with GitHub OIDC via azure/login?

### DISCUSSION THREAD

**Discussion by berney** [Azure/azure-storage-fuse#1449] [Q&A] [answered]
I am struggling with `blobfuse2 mount` to work in a GitHub Workflow that has authenticated to Azure with the `azure/login` action.
The `azure/login` action is working with GitHub OIDC, and I'm able to run `az` commands, including `az account get-access-token`, upload blobs etc., but I cannot get `blobfuse2` to work with `mode: azcli`.

I am using a GitHub's runner, I am NOT using self-hosted runners.

Is this meant to work?

I thought since I have a working `az`, the login has worked, that blobfuse2 should be able to leverage that login and also work, but it seems it doesn't work.

Does anyone have a working workflow?

## GitHub Workflow

```yaml
jobs:
  azure:
    name: Azure
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: az direct
        run: |
            az account show
            az group list
            az storage account list
            az storage container list --account-name ${{secrets.AZURE_STORAGE_ACCOUNT}}
            az storage container-rm list --storage-account ${{secrets.AZURE_STORAGE_ACCOUNT}}
            az storage blob list --account-name ${{secrets.AZURE_STORAGE_ACCOUNT}} --container-name ${{secrets.AZURE_STORAGE_COUNTAINER}} --auth-mode login --output table

      - name: Blob FUSE
        continue-on-error: true
        run: |
          sudo mkdir -p /mnt/blobfuse2
          sudo mkdir -p /mnt/blobfuse2tmp
          sudo blobfuse2 mount /mnt/blobfuse2 --config-file=config.yaml --tmp-path=/mnt/blobfuse2tmp
```

## Blobfuse2 `config.yaml`
This is my `config.yaml` for blobfuse2

```yaml
logging:
  level: log_debug
  file-path: "blobfuse2-logs.txt"
  type: base
azstorage:
  account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  container: ${{ secrets.AZURE_STORAGE_CONTAINER }}
  mode: azcli
```

## Blobfuse2 Logs

```
on Jul  8 10:08:11 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_TRACE [block_blob.go (163)]: BlockBlob::SetupPipeline : Setting up
Mon Jul  8 10:08:11 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_TRACE [block_blob.go (144)]: BlockBlob::createServiceClient : Getting service client
Mon Jul  8 10:08:11 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_DEBUG [azauth.go (82)]: azAuth::getAzAuth : Account: berneygithub, AccountType: BLOCK, Protocol: https, Endpoint: https://REDACTED.blob.core.windows.net/
Mon Jul  8 10:08:11 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_TRACE [block_blob.go (226)]: BlockBlob::SetPrefixPath : path 
Mon Jul  8 10:08:11 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_TRACE [block_blob.go (180)]: BlockBlob::TestPipeline : Validating
Mon Jul  8 10:08:11 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_DEBUG [utils.go (151)]: SDK(Retry) : =====> Try=1
Mon Jul  8 10:08:12 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_DEBUG [utils.go (151)]: SDK(Retry) : error AzureCLICredential: ERROR: Please run 'az login' to setup account.

Mon Jul  8 10:08:12 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_DEBUG [utils.go (151)]: SDK(Retry) : non-retriable error *errorinfo.nonRetriableError
Mon Jul  8 10:08:12 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_ERR [block_blob.go (199)]: BlockBlob::TestPipeline : Failed to validate account with given auth %!s(func() string=0x889cc0)
Mon Jul  8 10:08:12 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_ERR [azstorage.go (161)]: AzStorage::configureAndTest : Failed to validate credentials [AzureCLICredential: ERROR: Please run 'az login' to setup account.
]
Mon Jul  8 10:08:12 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_ERR [azstorage.go (101)]: AzStorage::Configure : Failed to validate storage account [failed to authenticate credentials for azstorage]
Mon Jul  8 10:08:12 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [failed to authenticate credentials for azstorage]
Mon Jul  8 10:08:12 UTC 2024 : blobfuse2[3036] : [/mnt/blobfuse2] LOG_ERR [mount.go (413)]: mount : failed to initialize new pipeline [failed to authenticate credentials for azstorage]
```

## Notes
After the `azure/login` step the workflow is able to run commands like `az storage account list` and `az storage container list` successfully. I've tested and it can upload blobs etc.

## Similar Discussions
I found https://github.com/Azure/azure-storage-fuse/discussions/1396, but I couldn't work out how to do it now that  azcli mode is available.

## Workaround

I was able to get it to work by modifying the configuration to this:

```yaml
allow-other: true
logging:
  level: log_debug
  file-path: "blobfuse2-logs.txt"
  type: base
azstorage:
  account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  container: ${{ secrets.AZURE_STORAGE_CONTAINER }}
  #mode: azcli
  mode: spn
  clientid: ${{ secrets.AZURE_CLIENT_ID }}
  tenantid: ${{ secrets.AZURE_TENANT_ID }}
  oauth-token-path: /token.txt
```

Where I have retrieved the GitHub OIDC token and saved it to a file. Note, I had to use the full file path.
Originally, I had just used `token.txt` (not full path), and it mounted successfully, but I couldn't list files in the mount.
Looking at the logs it couldn't find `token.txt` - it seems due to `sudo` and the CWD changing was causing problems after the initial mount.

I don't like that I have to retrieve and store the OIDC token.
This feels overly complicated and "wrong", especially when there was an existing, working, az login.
Does anyone have a better working solution?
