### ISSUE TITLE
Without sudo permission could NOT mount successful

### ISSUE THREAD

**Issue by yanboyang713** [Azure/azure-storage-fuse#1011]
### Which version of blobfuse was used?

```
[yanboyang713@archlinux mycontainer]$ blobfuse2 --version
blobfuse2 version 2.0.1
```

### Which OS distribution and version are you using?
I am using Arch Linux.
Using https://aur.archlinux.org/packages/azure-storage-fuse

### If relevant, please share your mount command.
If without sudo permission when I doing blobfuse2 mount, no any error show out, but when I list mount also show nothing. So, it is not mount successful.

```
[yanboyang713@archlinux ~]$ blobfuse2 mount /home/yanboyang713/mycontainer/ --config-file=/home/yanboyang713/blobfuseConfig.yaml
[yanboyang713@archlinux ~]$ blobfuse2 mount list
[yanboyang713@archlinux ~]$ sudo blobfuse2 mount list
```

However, if I use sudo permission mount will be successful.
```
sudo blobfuse2 mount /home/yanboyang713/mycontainer/ --config-file=/home/yanboyang713/fileCacheConfig.yaml --allow-other
```

```
[yanboyang713@archlinux mycontainer]$ blobfuse2 mount list
1 : /home/yanboyang713/mycontainer
```

### What was the issue encountered?
Without sudo permission could NOT mount successful

### Have you found a mitigation/solution?
not yet

### My yaml file
```
# Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
  ignore-open-flags: true

file_cache:
  path: /mnt/ramdisk/blobfuse2tmp
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: ####
  account-key: #####
  endpoint: https://####.blob.core.windows.net/
  mode: key
  container: mycontainer
```

Thanks for your helps.
