### ISSUE TITLE
blobfuse2 auth mode SPN does not pick up environment variable

### ISSUE THREAD

**Issue by Kirkius** [Azure/azure-storage-fuse#1037]
### Which version of blobfuse was used?
blobfuse2 version 2.0.1

### Which OS distribution and version are you using?
Ubuntu 22.04.1 LTS

### If relevant, please share your mount command.
`sudo blobfuse2 mount <mount-point> --config-file="<path-to-config.yml>"`

### What was the issue encountered?
When mounting a storage container with `type: adls` and `mode: spn` blobfuse2 does not accept the `clientsecret` to be passed as an environment variable. 
On the machine `echo $AZURE_STORAGE_SPN_CLIENT_SECRET` return the correct spn secret value. When using this value directly in the config.yml the mount works. 
Using `clientsecret: $AZURE_STORAGE_SPN_CLIENT_SECRET` returns error: `Error: failed to initialize new pipeline [failed to authenticate credentials for azstorage]`. 
Removing `clientsecret` from the config.yml return error: `Error: failed to initialize new pipeline [config error in azstorage [Client ID, Tenant ID or Client Secret not provided]]`

### Have you found a mitigation/solution?
Mitigation would be to revert to blobfuse v1, but our preference would be to use v2

### Please share logs if available.
No log available

### Sharing config.yml
```
allow-other: true

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: <path-to-cache-location>
  timeout-sec: 120
  max-size-mb: 20480 #20GB

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: <storage-account-name>
  container: <container-name>
  endpoint: https://<storage-account-name>.dfs.core.windows.net/
  mode: spn
  tenantid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  clientid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  clientsecret: $AZURE_STORAGE_SPN_CLIENT_SECRET
```
