### ISSUE TITLE
Health monitor output files are only readable by root

### ISSUE THREAD

**Issue by Tom-Newton** [Azure/azure-storage-fuse#1038]
### Which version of blobfuse was used?
blobfuse2 version 2.0.1

### Which OS distribution and version are you using?
Ubuntu 18.04

### If relevant, please share your mount command.
`mkdir /tmp/blobfuse_monitor_logs`
`sudo blobfuse2 mount /tmp/test_mount --config-file=<path-to-config>`

My config file includes:
```
health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /tmp/blobfuse_monitor_logs
  monitor-disable-list:
    - file_cache_monitor
    - memory_profiler
```

### What was the issue encountered?
Output files from the health monitor are not readable by non-root users. 

### Explanation:
I just discovered the new health monitor for blobfuse and it looks like it will be really useful. One small issue I'm having though is that the output files it produces are not readable by non root users:
`ls -l  /tmp/blobfuse_monitor_logs`
```
total 4
-rwxr-x--- 1 root root 1 Jan 21 18:39 monitor_4389.json
```
I can see [in the source code](https://github.com/Azure/azure-storage-fuse/blob/8ab54d9613a0e7dc4e2e1360ce76e3c178e28607/tools/health-monitor/internal/stats_export.go#L295) that these files are supposed to have `0755` permissions but the result looks more like `0750` to me (I only only learnt what these numbers mean this afternoon). 

I also tried running the `bfusemon` command manually:
`mkdir /tmp/blobfuse_monitor_logs2/`
`sudo bfusemon --pid=4389 --output-path=/tmp/blobfuse_monitor_logs2 --no-file-cache-monitor --no-memory-profiler --max-size-mb=65536 --stats-poll-interval-sec=10 --process-monitor-interval-sec=30 -no-network-profiler`

Now when I list this new directory I can see that the files have the correct permissions
```
ls -l /tmp/blobfuse_monitor_logs2/
total 4
-rwxr-xr-x 1 root root 1 Jan 21 18:45 monitor_4389.json
```
 
I think there is something about the way that `bfusemon` is launched when running the `blobfuse2` command that is causing the problem. Perhaps something related to `umask`.
