### ISSUE TITLE
Unable to create blobfuse2 temp directory for logs

### ISSUE THREAD

**Issue by brosahay** [Azure/azure-storage-fuse#1047]
### Which version of blobfuse was used?
    blobfuse2 version 2.0.1

### Which OS distribution and version are you using?
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=20.04
    DISTRIB_CODENAME=focal
    DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

### If relevant, please share your mount command.
    /usr/bin/blobfuse2 mount /mnt/userdata --tmp-path=/home/www-data/.blobfuse2/tmp --config-file=/home/www-data/.blobfuse2/config.yaml

### What was the issue encountered?
    While running the mount command as a service user(www-data), the following error is encountered:
    panic: Unable to create blobfuse2 temp directory for logs

### Have you found a mitigation/solution?
     Not yet, the particular user I am trying to mount it for is a service account.

### Please share logs if available.
```yaml
# Daemon configuration
foreground: true

# Common configurations
allow-other: false
# nonempty: true
default-working-dir: /home/www-data/.blobfuse2/working_dir

# Logging configurations
logging:
  type: syslog
  level: log_debug
  file-path: /home/www-data/.blobfuse2/blobfuse2.log

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

# Libfuse configuration
libfuse:
  default-permission: 0644
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/www-data/.blobfuse2/tmp
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name:
  account-key:
  endpoint: 
  mode: key
  container: 
```

```log
$ ls -laRt
.:
total 12
drwxrwxr-x 4 www-data www-data 4096 Jan 31 02:22 .blobfuse2
drwxr-xr-x 3 www-data www-data 4096 Jan 30 17:35 .
drwxr-xr-x 4 root     root     4096 Jan 15 19:17 ..

./.blobfuse2:
total 20
drwxrwxr-x 4 www-data www-data 4096 Jan 31 02:22 .
-rw-r--r-- 1 www-data www-data 1000 Jan 31 02:22 config.yaml
drwxrwxr-x 2 www-data www-data 4096 Jan 31 02:17 tmp
drwxrwxr-x 2 www-data www-data 4096 Jan 31 02:17 working_dir
drwxr-xr-x 3 www-data www-data 4096 Jan 30 17:35 ..

./.blobfuse2/tmp:
total 8
drwxrwxr-x 4 www-data www-data 4096 Jan 31 02:22 ..
drwxrwxr-x 2 www-data www-data 4096 Jan 31 02:17 .

./.blobfuse2/working_dir:
total 8
drwxrwxr-x 4 www-data www-data 4096 Jan 31 02:22 ..
drwxrwxr-x 2 www-data www-data 4096 Jan 31 02:17 .

$ /usr/bin/blobfuse2 mount /mnt/userdata --tmp-path=/home/www-data/.blobfuse2/tmp --config-file=/home/www-data/.blobfuse2/config.yaml
panic: Unable to create blobfuse2 temp directory for logs

goroutine 1 [running]:
github.com/Azure/azure-storage-fuse/v2/common/log.init.0()
	/mnt/vss/_work/1/s/azure-storage-fuse/common/log/logger.go:233 +0x1ab
```
