### ISSUE TITLE
Support Azure AD workload identity authentication

### ISSUE THREAD

**Issue by jerrychenhf** [Azure/azure-storage-fuse#1049]
### Which version of blobfuse was used?
blobfuse2-2.0.1

### Which OS distribution and version are you using?
Ubuntu 20.04 LTS

### What was the issue encountered?
Basically, we are trying to use blobfuse2 in AKS pod to access Azure DataLake Gen2 storage.
The authentication method we choose is to use is Azure AD workload identity which federates managed identity with AKS service account. This method is somewhat different with the existing managed identity authentication binding with VM instance (MSI).

The current blobfuse(2) seems to not support this method. 

Microsoft Azure AKS replaced its original pod-managed identity with with [Azure Active Directory (Azure AD) workload identities](https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identities-overview) (preview), which integrate with the Kubernetes native capabilities to federate with any external identity providers. This approach is simpler to use and deploy.

Refer to https://azure.github.io/azure-workload-identity/docs/introduction.html for more details.

The basic use scenario is to access Azure cloud resources (such as cloud storage) from Kubernetes (such as AKS) workload using Azure managed identity federated with Kubernetes service account. The credential environment variables in pod projected by Azure AD workload identity are like following:

AZURE_AUTHORITY_HOST: (Injected by the webhook, https://login.microsoftonline.com/)

AZURE_CLIENT_ID: (Injected by the webhook)

AZURE_TENANT_ID: (Injected by the webhook)

AZURE_FEDERATED_TOKEN_FILE: (Injected by the webhook, /var/run/secrets/azure/tokens/azure-identity-token)

The token in the file pointed by AZURE_FEDERATED_TOKEN_FILE is a JWT (JASON Web Token) client assertion token which we can use to request to AZURE_AUTHORITY_HOST (url is  AZURE_AUTHORITY_HOST + tenantId + "/oauth2/v2.0/token")  for a AD token which can be used to directly access the Azure cloud resources.

### Have you found a mitigation/solution?
No

### Please share logs if available.

Since the Azure AD workload identity is very important step for AKS to deploy and run easily in a cloud environment. AWS and GCP has supported this long time ago.
It is with great value for blobfuse to support this authentication method.

The technical information for how to implement can be found from azure identity package from azure sdk for python:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/workload_identity.py

**Comment by andyzhangx** [comment]
@cvvz is working on workload identity support for all azure csi drivers. could you take a look whether there are potential gap for blobfuse support with workload identity?

**Comment by vibhansa-msft** [comment]
@andyzhangx : I went through [this](https://learn.microsoft.com/en-us/samples/azure-samples/azure-ad-workload-identity/azure-ad-workload-identity/) document. And it says workload identity to AAD token exchange can be done using MSAL or AzIdentity. Is this understanding, correct?
Basically, we have a security token given to Kubernetes account and then we take this token and retrieve a AAD token to access Azure resources.

**Comment by jerrychenhf** [comment]
Thanks @andyzhangx, @vibhansa-msft for quick response.
The token exchange process is very similar to the process of request a AAD token using a client secret. Below are the key request code from azure identity python SDK.

For requesting token with client secret:
 def _get_client_secret_request(self, scopes: Iterable[str], secret: str, **kwargs: Any) -> HttpRequest:
        data = {
            "client_id": self._client_id,
            "client_secret": secret,
            "grant_type": "client_credentials",
            "scope": " ".join(scopes),
        }
        request = self._post(data, **kwargs)
        return request

for exchange AAD token with the JWT token (assertion) (read from the token file pointed by AZURE_FEDERATED_TOKEN_FILE)
def _get_jwt_assertion_request(
            self,
            scopes: Iterable[str],
            assertion: str,
            **kwargs: Any
    ) -> HttpRequest:
        data = {
            "client_assertion": assertion,
            "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
            "client_id": self._client_id,
            "grant_type": "client_credentials",
            "scope": " ".join(scopes),
        }

        request = self._post(data, **kwargs)
        return request

The endpoint of the post is formed by: AZURE_AUTHORITY_HOST + AZURE_TENANT_ID + "/oauth2/v2.0/token"

**Comment by cvvz** [comment]
There are 2 steps to use blobfuse in AKS: provision and mount. For the provision step, blob CSI is going to support workload identity soon. For the mount step, so far [blobfuse supports 4 kinds of auth type: account key, SAS, SP and MSI](https://github.com/Azure/azure-storage-fuse#environment-variables), not include **managed identity federated with Kubernetes service account**, which AKS depends on.

**Comment by cvvz** [comment]
Hi @jerrychenhf , we are working on this feature. I think it would be supported in blob CSI driver by the end of March, please stay tuned.

**Comment by cvvz** [comment]
@jerrychenhf Could you please take a look at this comment: https://github.com/Azure/AKS/issues/3432#issuecomment-1438213861? Is this the same use case you want? That is to say, application with different ServiceAccount has different permission to access storage?

**Comment by jerrychenhf** [comment]
@cvvz Not strictly the same. We don't have to handle multiple service accounts. Our use case uses a single service account mapping to user assigned identity for accessing the storage.

**Comment by vibhansa-msft** [comment]
Blobfuse right now relies on a older SDK which does not have this support. There is a newer version of SDK that has the reqired support but due to resource constraints we are not able to migrate to that. This migration will be a major code change and will require some time to stabilize as well. Given the constraints it might not be feasible for now.

**Comment by andyzhangx** [comment]
> Blobfuse right now relies on a older SDK which does not have this support. There is a newer version of SDK that has the reqired support but due to resource constraints we are not able to migrate to that. This migration will be a major code change and will require some time to stabilize as well. Given the constraints it might not be feasible for now.

@vibhansa-msft what do you mean older sdk? do you mean azure sdk1? FYI. we have successfully added managed identity support  two months ago in adal lib: https://github.com/Azure/go-autorest/pull/719

**Comment by vibhansa-msft** [comment]
We are isomg track-1 SDK. Track-2 SDK which integrates with new identity package has just been GAed and Blobfuse has not planned any integration with that as of now.

**Comment by schwichti** [comment]
I am a little bit lost in the discussion. Did I get it right that Blobfuse currently does not support Azure Workload Identities and that the support is not planned? Are there alternatives?

**Comment by vibhansa-msft** [comment]
Yes it does not support as of now, and its not planned in near future as well. We might need to bring this topic up to our higher levels and get approvals as we are constrained by resources right now. For the alternative part, I am afraid there is none for now. If there is any other way to get the token, we can make a hacky way where user can provide token in form of a file and blobfuse just start using it for all its REST calls.

**Comment by cvvz** [comment]
@jerrychenhf @sarav-ks  @schwichti 
I want to make sure that I understand your needs correctly, please point out if I'm wrong.

---

There are two steps for a Pod to use a volume: provisioning and mounting.

1. For the provisioning process:

For the provisioning process, actually, it's the csi driver's responsibility to interact with Azure storage API to create storage resource in Azure. So, the authorization is to verify whether **csi driver's SA/WI** has the permission to provision volume.

2. For the mounting process:

Before mounting, we need to make sure the Pod has the permission to mount to the volume, csi driver would get the **Pod's SA/WI** first, then decide whether the Pod has the permission to mount the volume or not.

If I understand correctly:
1. You want to mount the volume by using Pod's SA/WI as authentication, that is to say, some Pods with specific SA/WI can mount to the volume while some Pods are not.
2. You don't care too much about how csi driver provision volume for you.

**Comment by schwichti** [comment]
Yes, your summary is correct. I can give you more background information:
* I do not want to store passwords in Kubernetes secrets
* I want only the pods to have access to the storage account that really need it. That is to restrict the attack surface.
* The pod that has access to the storage account uses third party software which does not support SAS tokens.

**Comment by schwichti** [comment]
It turned out that we cannot use Azure Blobfuse Driver until https://github.com/Azure/azure-storage-fuse/issues/1137 is resolved.

**Comment by vibhansa-msft** [comment]
Closing this as read of token from a given file feature has been added to main code and will be available in our next release. #1137 talks about fcntl but as of now we do not have plans to support that. Will be taken up as low priority item later. Feel free to reopen this, if the next release does not work for you with the token reading mechanism.

**Comment by cvvz** [comment]
We are gonna implement this feature, below is the specific use case, could you please take a look and see if it satisfies your requirement? Any suggestion would be helpful, thanks! cc @jerrychenhf @schwichti @sarav-ks

Create a storage account and a WLI and grant enough permissions for the WLI to access the storage account
Create a Kubernetes Storage Class or PV that explicitly specify the storage account and fileshare(for azurefile)/container(for blob) you created, of course, you don't have to specify the secret of the storage account.
Create Kubernetes service account
Establish federated identity credential between Service Account and WLI
Deploy a pod that references the service account created in the previous step, and a PVC that uses the PV/storage class you created.
The pod can start up normally and mount the volume successfully. Any other Pods that do not reference the service account can not start up and the failure message is that it doesn't have permission to access the storage account.
No credential will be exposed on AKS in above steps.

**Comment by schwichti** [comment]
@cvvz yes, your description sounds good. Currently, this feature has very low importance for us.

**Comment by hirushanlk** [comment]
@cvvz is that feature to support workload identity setting for static persistent volume mount when working with blobfuse2 and CSI driver for AKS implemented and ready to use? 

I have followed the same [steps](https://github.com/Azure/azure-storage-fuse/issues/1049#issuecomment-1805054411) you have mentioned above and it returns the following error after creating the pod.  
**`GRPC call returned with an error: rpc error: code = Unknown desc = exit status 1 Error: failed to initialize new pipeline [failed to get credential]`**

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-datalake
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
    - --use-adls=true
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: nimdatalake_mycontainer
    volumeAttributes:
      containerName: mycontainer
      storageAccount: nijmcfgdatalake
      resourceGroup: nim-datalake-rg
      AzureStorageAuthType: msi
      AzureStorageIdentityClientID: 00000000-0000-0000-0000-000000000000
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-datalake
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-blob-datalake
  storageClassName: azureblob-fuse-premium
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 00000000-0000-0000-0000-000000000000
  labels:
    azure.workload.identity/use: "true"
  name: nim-wi-sa
  namespace: default
```

```
apiVersion: v1
kind: Pod
metadata:
  name: datalake-test-pod
  labels: 
    azure.workload.identity/use: "true"
  namespace: default
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  serviceAccountName: nim-wi-sa
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    name: datalake-test-pod
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/azureblob/data; sleep 60; done
    volumeMounts:
    - name: blob01
      mountPath: "/mnt/azureblob"
  volumes:
  - name: blob01
    persistentVolumeClaim:
      claimName: pvc-blob-datalake 
```
