### ISSUE TITLE
File in mounted directoy can be created and deleted but not modified

### ISSUE THREAD

**Issue by StefanHauser** [Azure/azure-storage-fuse#1055]
### Which version of blobfuse was used?
2.0.1

### Which OS distribution and version are you using?
Suse Enterprise 15 SP1

## Config File
```
azstorage:

  account-name: myaccount

  endpoint: https://myaccount.blob.core.windows.net 

  mode: msi

  container: input

file_cache:
  path: /home/cftuserI/tmp/input

logging:

  type: base

  level: log_info

  file-path: /home/cftuserI/.blobfuse2/blobfuse2.log
```

### What was the issue encountered?
Files in the mounted directory can be created and removed but not edited. 
Steps to reproduce:
```
touch test.txt
vim test.txt
```
 Creating and editing the file directly with `vim` works

The issue is encountered as root and as non root user and independent whether I use `allow_other` option or not. When mounting as root (with allow other option), these are the permissions of my mounted directory:
```
drwxrwxrwx 2 root root 4096 Feb  7 16:05 MAINFRAME
drwxrwxrwx 2 root root 4096 Feb  7 16:17 SAFIRA
drwxrwxrwx 2 root root 4096 Feb  8 08:26 TEST
-rwxrwxrwx 1 root root    0 Feb  8 09:35 test.txt
-rwxrwxrwx 1 root root    0 Feb  8 09:43 txt
-rwxrwxrwx 1 root root    5 Feb  8 10:19 test-shause.txt
-rwxrwxrwx 1 root root    0 Feb  8 10:54 root-test.txt
```
When mounting as non root user without `allow_other` option, these are the permissions of the mounted directory:
```
drwxrwxr-x 2 cftuserI users 4096 Feb  7 16:05 MAINFRAME
drwxrwxr-x 2 cftuserI users 4096 Feb  7 16:17 SAFIRA
drwxrwxr-x 2 cftuserI users 4096 Feb  8 08:26 TEST
-rwxr-xr-x 1 cftuserI users    0 Feb  8 10:54 root-test.txt
-rwxr-xr-x 1 cftuserI users    5 Feb  8 10:19 test-shause.txt
-rwxr-xr-x 1 cftuserI users    0 Feb  8 09:35 test.txt
-rwxr-xr-x 1 cftuserI users    0 Feb  8 09:43 txt
```
### Have you found a mitigation/solution?
No

### Please share logs if available.
Receiving ` E212: Can't open file for writing`.
