### ISSUE TITLE
Mounting fails with unknown option `--log-file-path` on Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by maitre-matt** [Azure/azure-storage-fuse#1072]
### Which version of blobfuse was used?

Built-in version in Azure Kubernetes Service (AKS), installed using `az aks update --enable-blob-driver --resource-group xxx --name xxx`

### Which OS distribution and version are you using?

The base container image is `mcr.microsoft.com/dotnet/runtime:7.0-jammy-amd64`.

### If relevant, please share your mount command.

Kubernetes `PersistentVolume` config:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xxx
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: azureblob-fuse-retain
  mountOptions:
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10
  - --tmp-path=/mnt/ram
  - --log-file-path=/tmp/azureblob.log
  - --log-type=base
  - -o allow_other
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: xxx
    volumeAttributes:
      resourceGroup: xxx
      storageAccount: xxx
      containerName: xxx
      AzureStorageAuthType: MSI
      AzureStorageIdentityResourceID: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxx
      protocol: fuse
```

### What was the issue encountered?

The container is stuck in `State=ContainerCreating` with `kubelet` event: `  Warning  FailedMount MountVolume.MountDevice failed for volume "testmmaitrezeek-blobfuse" : rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 fuse: unknown option '--log-file-path=/tmp/azureblob.log'
no config filedone reading env varsURI token request URL printed out http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&mi_res_id=/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxx&resource=https://storage.azure.com/
, output:`

### Have you found a mitigation/solution?

Mounting succeeds without the options `--log-file-path` and `--log-type`.

### Please share logs if available.

I would like to get logs but enabling them prevents container start.
