### ISSUE TITLE
Mounted blob produces endless directory loop of the mounted name

### ISSUE THREAD

**Issue by aristeidistyr** [Azure/azure-storage-fuse#1073]
### Which version of blobfuse was used?
BlobFuse 2.0.2

### Which OS distribution and version are you using?
Ubuntu 20.02

### If relevant, please share your mount command.
sudo blobfuse2 mount ./[mount folder] --config-file=./home/blobfuse2conf/myconfig.yml
Config file has not changed from last time.
Using MSI and System assigned identity with correct RBAC on the storage account.

### What was the issue encountered?
The mount completes successfully but now instead of seeing the contents of the container we see an endless loop of the name of the mount: so for example:
 #cd [mount folder]

[mount folder]#ls 
result:
[mount folder]

 Then cd [mount folder]
[mount folder]#ls 
result:
[mount folder]

....To eternity.
### Have you found a mitigation/solution?
No

**Comment by vibhansa-msft** [comment]
Is this a HNS storage account or non-HNS?
Can you share your config file as well.

**Comment by aristeidistyr** [comment]
Account is StorageV2 (general purpose v2) (datalake storage)
Hierarchical namespace: Enabled


Config file:

```
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/blobfuse2conf/tempcache
  timeout-sec: 120
  max-size-mb: 61.440

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: [thestorageaccountname]
  endpoint: https://[thestorageaccountname].blob.core.windows.net
  mode: msi
  container: [thecontainername]
  appid: [THEAPPIDOFTHESSYSTEMASSIGNEDID]
```
Obviously the folder locations are as specified.
