### ISSUE TITLE
AKS 1.25.5 may have broken changes to the blobfuse2 csi driver?

### ISSUE THREAD

**Issue by pa-mc** [Azure/azure-storage-fuse#1078]
### Which version of blobfuse was used?

```
$ kubectl exec -it csi-blob-node-jh2pg -c blob -n kube-system -- /bin/sh

# blobfuse2 version
blobfuse2 version: 2.0.2

# blobfuse -v
blobfuse 1.4.5

# mount | grep -i blobfuse
blobfuse2 on /var/lib/kubelet/pods/ff2c91e1-31b0-46cf-9cdb-3954dd009cfd/volumes/kubernetes.io~csi/pv-stpabackupsprod-blob-container/mount type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
blobfuse2 on /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/a827afe57ea9da516011d9c85fceef41165a4bda0ace1d794dbb683b93ddd556/globalmount type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```

```
$ kubectl logs csi-blob-node-jh2pg -c blob -n kube-system -f
.
.
.
I0307 16:02:55.576469    5748 utils.go:82] GRPC response: {"name":"blob.csi.azure.com","vendor_version":"v1.19.1"}
I0307 16:02:55.789446    5748 utils.go:75] GRPC call: /csi.v1.Identity/GetPluginInfo
.
.
.
```

### Which OS distribution and version are you using?

> This is the entire AKS cluster (control node + work node_pools): `1.25.5`

> This is the OS on the `blob.csi.azure.com` Pod in AKS

```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

> This is the OS of a running Pod that have an BlobFuse mounted inside it

```
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### If relevant, please share your mount command.

Using k8s PV & PVCs utlizing the Blob Fuse Storage Class. Here is the blobfuse storageclass yaml manifest file:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azureblob-fuse-premium
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: 'true'
provisioner: blob.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Delete
mountOptions:
  - '-o allow_other'
  - '--file-cache-timeout-in-seconds=120'
  - '--use-attr-cache=true'
  - '--cancel-list-on-mount-seconds=10'
  - '-o attr_timeout=120'
  - '-o entry_timeout=120'
  - '-o negative_timeout=120'
  - '--log-level=LOG_WARNING'
  - '--cache-size-mb=1000'
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

### What was the issue encountered?
It almost as if there is a delay of mounting or even more peculiar that you have to `ls` certain directory, before you can see your mounted contents. Please see a series of `ls` commands output below. 

> As you can see below, as soon as `exec` into the pod, you cannot see the mounted content, however, I'm 1000% sure everything is mounted correctly. Because I can see that the blobfuse is trying to call `I0307 20:19:45.589856    5748 utils.go:75] GRPC call: /csi.v1.Node/NodePublishVolume`, and the outputs suggest everything is mounted correctly. 

> As you can see, if I keep `ls` on certain directory, eventually the mounted contents will show up, this is really weird... 

> Note, this is a 5T+ mount. Not sure if that matters, because I have the exact setup for another AKS cluster, it's working fine. The only difference is that the other AKS cluster is running on `1.24.9`

```shell
$ kubectl exec -it -n pa-data-services deployments/orientdbservice -- /bin/bash
Defaulted container "orientdbservice" out of: orientdbservice, orientdbservicehandler
root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/
ls: cannot access '/mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/': No such file or directory
root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/
stpabackupsprod
root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/
blobfuse-files  orientdb-databases  provision-foodnote-io  ssl-certificates
root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/
ls: cannot access '/mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/': No such file or directory
root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/
demo  isolated-tenants  prod  test  trial
root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/
# For privacy reasons, there is just a lot of zip files in this directory. 
```

### Have you found a mitigation/solution?
No.

**Comment by andyzhangx** [comment]
@vibhansa-msft

**Comment by vibhansa-msft** [comment]
Can you confirm this is a FNS (non-HNS) account. If so, such account does not have concept of a directory and we rely on special blob called directory-stub in these cases. If such stubs are missing Blobfuse will not be able to list the directories correctly. To support such data set you need to provide "--virtual-directory=true" cli option on mount. Kindly try this out and let me know if this works for you.

**Comment by pa-mc** [comment]
Hi @andyzhangx & @vibhansa-msft, thanks for the quick coordiantion & replies :) 

I assumed HNS meaning Hierarchical Namespace Storage? If that's the case, yes, the storage account i'm using has HNS disabled. 
<img width="388" alt="Screenshot 2023-03-07 at 22 36 22" src="https://user-images.githubusercontent.com/98042349/223613274-26697c2b-adef-48d0-b23a-a769aaa12ff8.png">

Regarding the `directory-stub`, are those file-icon-like files are the `directory-stub` (screenshots in the expandable below)? It sounds like the inconsistency of our `directory-stub` is the problem? I will give the `--virtual-directory=true` option a try to our storageclass. 

On a related note, is this something new with `AKS 1.25.5`, that is no longer tolerate missing of `directory-stub`? Because my `AKS 1.24.9` did not suffer this issue. It has the same azure blob store mounted, and it will list the directories correctly. 

<details><summary>more azure blob store screenshots></summary>

<img width="315" alt="Screenshot 2023-03-07 at 22 37 40" src="https://user-images.githubusercontent.com/98042349/223613449-53cdc977-1b77-4326-ba2f-835cf484f3a6.png">

<img width="491" alt="Screenshot 2023-03-07 at 22 39 28" src="https://user-images.githubusercontent.com/98042349/223613725-32bcb454-3433-48a8-9d81-f7ce83ca9603.png">

<img width="396" alt="Screenshot 2023-03-07 at 22 40 09" src="https://user-images.githubusercontent.com/98042349/223613780-5ad603e5-253c-4de3-a2b2-af30f9097a79.png">

</details>

**Comment by vibhansa-msft** [comment]
Yes HNS (Hierarchical NameSpace) is disabled in your case so missing directory stub might be an issue here.
Directory-stubs are 0 byte blobs that have the same name as directory so in portal if you filter on your directory name you will one directory icon and a 0-byte blob with exactly the same name.
For different AKS version, can you confirm both were using blobfuse2? if older version was configured to use blobfuse1.x then you might not observe the issue there.

**Comment by vibhansa-msft** [comment]
@andyzhangx  : Just for my understanding, which option in above config control whether user will go through v2 or v2 blobfuse. Or it can not be controlled from user config?

**Comment by pa-mc** [comment]
@vibhansa-msft Yup, you are correct! My other `AKS 1.24.9` is using blobfuse v1, and that's why, like you said, even if I did not have the proper `directory-stub`, it still worked fine. I tried `--virtual-directory=true`, but still not working tho. I will post some context in the next reply :) 

```
# This is the AKS 1.25.5
❯ kubectl config current-context
pa-data-devtest-aks

❯ kubectl exec -it csi-blob-node-jh2pg -c blob -n kube-system -- /bin/sh
# mount | grep -i blobfuse
blobfuse2 on /var/lib/kubelet/pods/c82953e1-7e37-4696-9659-1d73e9a118e1/volumes/kubernetes.io~csi/pv-stpabackupsprod-blob-container/mount type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
blobfuse2 on /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/a827afe57ea9da516011d9c85fceef41165a4bda0ace1d794dbb683b93ddd556/globalmount type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```

```
# This is the AKS 1.24.9
❯ kubectl config current-context
pa-data-prod-aks

❯ kubectl exec -it csi-blob-node-jh5hb -c blob -n kube-system -- /bin/sh
# mount | grep -i blobfus
blobfuse on /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/a827afe57ea9da516011d9c85fceef41165a4bda0ace1d794dbb683b93ddd556/globalmount type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
blobfuse on /var/lib/kubelet/pods/9c93728b-319c-428c-a37b-279d4ef13d56/volumes/kubernetes.io~csi/pv-stpabackupsprod-blob-container/mount type fuse (rw,relatime,user_id=0,group_id=0)
```

**Comment by vibhansa-msft** [comment]
Interesing. So if you do not have directory-stub in your account this new cli option is a must for now. Coming back to your listing problem can you confirm on whether you dont see anything at all or its more like you see files and no directories.

**Comment by vibhansa-msft** [comment]
If possible can you also enable log_debug in blobfuse and share the log files which capture your list command resulting into no listng.

**Comment by pa-mc** [comment]
> Interesing. So if you do not have directory-stub in your account this new cli option is a must for now. Coming back to your listing problem can you confirm on whether you dont see anything at all or its more like you see files and no directories.

I think I do have `directory-stub` just not all of the directories, not sure if that matters. You can see more azure blob screenshots in [this comment](https://github.com/Azure/azure-storage-fuse/issues/1078#issuecomment-1459348966)

Regarding the `ls` problem. Yeah, it's more likely eventually I can see all the directories and files. As you can see from the logs below. As soon as I `exec` into the pod and do a `ls` on some directory (which has a lot of zip files in it), but there is no files to be found. Then I just keep do `ls` starting from the `/mnt` point, and as you can see below, all directories just start to show themselves. The last `ls`, for pracy reasons, not showing all the zip files. But I do see those zip files. 

```
$ kubectl exec -it -n pa-data-services deployments/orientdbservice -- /bin/bash
Defaulted container "orientdbservice" out of: orientdbservice, orientdbservicehandler

root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/
ls: cannot access '/mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/': No such file or directory

root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/
stpabackupsprod

root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/
blobfuse-files  orientdb-databases  provision-foodnote-io  ssl-certificates

root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/
ls: cannot access '/mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/': No such file or directory

root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/
demo  isolated-tenants  prod  test  trial

root@orientdbservice-58c79ffb79-f74w9:/orientdb# ls /mnt/stpabackupsprod/orientdb-databases/prod/2023-03-07/
# For privacy reasons, there is just a lot of zip files in this directory. 
```

**Comment by vibhansa-msft** [comment]
Can you try removing '--cancel-list-on-mount-seconds=10' and validate.

**Comment by pa-mc** [comment]
> Can you try removing '--cancel-list-on-mount-seconds=10' and validate. If this works, I can explain the failure here.

Hey hey, that worked! However, could you expand a bit on this option? According to the documenation, it seems to suggest if I have this option turned on, then it will not charge on mounting? Because mounting azure blob store is by default a `list blob` action, which charges money, right?

```
--cancel-list-on-mount-seconds=<TIMEOUT IN SECONDS>: Time for which list calls will be blocked after mount. ( prevent billing charges on mounting)
```

**Comment by vibhansa-msft** [comment]
When you mount any file-system kernel by default tries to list the root, sometimes it tries to do this multiple times. There were customers who had issue with this as they had a large number of files. If kernel tries to do implicit listing multiple times customer will get charged for those listBlob calls. So, we provided this option so disable directory listing for initial few seconds after mounting. As you have configured it to 10, listing api will not work for 10 seconds after mount and post that it will return back to normal mode. If you are concerned with this cost too you can keep the option on and try listing after 10-15 seconds and everything shall work fine.

**Comment by vibhansa-msft** [comment]
If this solves your issue, kindly close this item here.

**Comment by pa-mc** [comment]
@vibhansa-msft Thank you so much for the help! I add back the `- '--cancel-list-on-mount-seconds=5'` option but reduced it to 5 seconds. 

However, I think it's still the `--virtual-directory=true` you suggested was the ultimate solution to my problem :) Here is my working config in case other people may bump into it in the future as well. 

My AKS cluster: `1.25.5` + Azure Official Blob Fuse CSI Driver `2.0.2`

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yourPVName
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: yourPVCName
    namespace: yourNamespace
  # Retain allows the feature that even deleting the PVC & PV the external Azure Blob Container or Azure File Shares WILL NOT get deleted. 
  # That is quite important, because that means even somehow the ENTIRE Kubernetes cluster is gone. We still have our data.
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  csi:
    # This driver, however, does not come pre-installed when creating an AKS. Also, it seems to be in preview. 
    # So there is an elaborated steps to enable and install it. 
    # See the README.md section of: ## About blob-csi-driver
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: yourVolumeHandle
    volumeAttributes:
      resourceGroup: yourResourceGroup
      containerName: yourContainerName
    nodeStageSecretRef:
      name: yourSecretRef
      namespace: yourNamespace
  mountOptions:
    - '-o allow_other'
    - '--file-cache-timeout-in-seconds=120'
    - '--use-attr-cache=true'
    - '--cancel-list-on-mount-seconds=5'
    - '-o attr_timeout=120'
    - '-o entry_timeout=120'
    - '-o negative_timeout=120'
    - '--log-level=LOG_WARNING'
    - '--cache-size-mb=1000'
    - '--virtual-directory=true'
```
