### ISSUE TITLE
Why not use DFS endpoint when upload a file with ADLS type (compare with goofys)?

### ISSUE THREAD

**Issue by Lyndon1994** [Azure/azure-storage-fuse#1090]
### Which version of blobfuse was used?
v2

### Which OS distribution and version are you using?
ubuntu18.04

### If relevant, please share your mount command.
```
go build -tags=fuse2
./azure-storage-fuse mount --config-file=./sampleFileCacheConfig.yaml /home/azureuser/mnt/blobfusev2
```
sampleFileCacheConfig.yaml:
```
# Refer ./setup/baseConfig.yaml for full set of config parameters

allow-other: true

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/azureuser/mnt/tmp_file_v2
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: xxx
  account-key: xxx
  endpoint: https://xxx.dfs.core.windows.net
  mode: key
  container: test
```

### What was the issue encountered?

I compared the write file performance of **blobfusev2** and **goofys** and found that blobfusev2 is much slower. 
I found that they were all written concurrently, but the requested URLs were different. Blobfuse uses the **blob** API, and goofys uses the **adls** API. I don't know if this has anything to do with it. Why doesn't blobfuse use the adls api? For what consideration?

![image](https://user-images.githubusercontent.com/13145082/226522645-5fc7df25-350c-46da-9c93-1e79e1af7aaf.png)

blobfuse's url: https://xxx.blob.core.windows.net/test/Benchmark/blobfusev2/0000.txt
goofys's url: https://xxx.dfs.core.windows.net/test/Benchmark/goofys/0000.txt?action=append&position=948961280
doc: https://learn.microsoft.com/vi-vn/rest/api/storageservices/datalakestoragegen2/path/update#request-body
