### ISSUE TITLE
Can create the file, but can't create the folder.

### ISSUE THREAD

**Issue by run-stop** [Azure/azure-storage-fuse#1094]
### Which version of blobfuse was used?
blobfuse2 version 2.0.2

### Which OS distribution and version are you using?
Ubuntu 22.04.2 LTS

### If relevant, please share your mount command.
```bash
blobfuse2 mount /mnt/backup/ --config-file .config/baseConfig.yaml
```

The baseConfig.yaml file:
```yaml
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

attr_cache:
  timeout-sec: 7200

file_cache:
  path: ~/.cache/blobfuse2
  timeout-sec: 120
  max-size-mb: 4096

azstorage:
  type: block
  virtual-directory: true
  account-name: <redacted>
  account-key: <redacted>
  endpoint: https://<redacted>.blob.core.windows.net
  mode: key
  container: backup
```
The `/etc/fuse.conf` file has the `user_allow_other` option.

### What was the issue encountered?
I'm mounting the `/mnt/backup` folder, and everything looks good. I can create and delete files in the `/mnt/backup` as expected. 

If I try to create a folder `x`, the operation will fail:
```bash
$ mkdir /mnt/backup/x
mkdir: cannot create directory ‘/mnt/backup/x’: File exists
```
The directory `x` is not visible from UNIX shell side, however if I log in to the Azure portal, I can browse to the blob, and find that the folder `x` has been created.

### Have you found a mitigation/solution?
No, but I have made number of attempts with or without the `virtual-directory: true` option. I've also checked UNIX permissions, and tried the whole process as both unprivileged and the super user.
This very same Azure storage is working with blobfuse1 on an old system.

### Please share logs if available.

The log file shows some trace and one error message:
```
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_DEBUG [attr_cache.go (465)]: AttrCache::GetAttr : x served from cache                                                                [20/1904]
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_DEBUG [file_cache.go (1161)]: FileCache::GetAttr : x does not exist in storage                                                                
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [libfuse_handler.go (392)]: Libfuse::libfuse_mkdir : x                                                                                  
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [attr_cache.go (221)]: AttrCache::CreateDir : x                                                                                         
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [azstorage.go (191)]: AzStorage::CreateDir : x                                                                                          
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [block_blob.go (274)]: BlockBlob::CreateDirectory : name x                                                                              
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [block_blob.go (912)]: BlockBlob::WriteFromBuffer : name x                                                                              
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [file_cache.go (1149)]: FileCache::GetAttr : x                                                                                          
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [attr_cache.go (455)]: AttrCache::GetAttr : x                                                                                           
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [block_blob.go (522)]: BlockBlob::GetAttr : name x                                                                                      
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [block_blob.go (469)]: BlockBlob::getAttrUsingList : name x                                                                             
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [block_blob.go (536)]: BlockBlob::List : prefix x, marker      
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [block_blob.go (431)]: BlockBlob::getAttrUsingRest : name x/                                                                            
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_TRACE [block_blob.go (505)]: BlockBlob::getAttrUsingList : So far retrieved 0 objects in 1 iterations                                         
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_ERR [block_blob.go (512)]: BlockBlob::getAttrUsingList : blob x does not exist                                                                
mrt 23 17:19:38 PC blobfuse2[25260]: LOG_DEBUG [file_cache.go (1161)]: FileCache::GetAttr : x does not exist in storage 
```
