### ISSUE TITLE
[AKS1.25.5 Upgrade] Mounted storage account blob containers does not properly work

### ISSUE THREAD

**Issue by danilo-santoro** [Azure/azure-storage-fuse#1106]
### Which version of blobfuse was used?

blobfuse v2.0.2

### Which OS distribution and version are you using?

I encountered this issue after upgrading Azure Kubernetes to version 1.25.5.
I also reproduced the same issue using an ubuntu 22.10 with blobfuse2 v2.0.2 and mounting the same blob container.

### If relevant, please share your mount command.

I'm mounting the blob container using the following storage class:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=120
- --use-attr-cache=true
- --cancel-list-on-mount-seconds=10
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --log-level=LOG_WARNING
- --cache-size-mb=1000
parameters:
  skuName: Premium_LRS
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

### What was the issue encountered?

When I try to create a folder or a file in the mounted blob container, the following message is shown:

<img width="614" alt="Screenshot 2023-04-07 alle 21 38 14" src="https://user-images.githubusercontent.com/108342742/230667234-b958d173-3126-4ac9-9839-5c8310931f78.png">

and

<img width="758" alt="Screenshot 2023-04-07 alle 21 40 55" src="https://user-images.githubusercontent.com/108342742/230667606-5176b4af-ba61-42c0-a2a7-a7b410b6bfc4.png">

### Have you found a mitigation/solution?

no

### Please share logs if available.

This is the storage account configuration

<img width="1093" alt="Screenshot 2023-04-07 alle 21 41 47" src="https://user-images.githubusercontent.com/108342742/230667710-37225d21-1a1a-4331-9779-3ec50ccdc169.png">

These are the logs collected on ubuntu box where I reproduced the issue

![image](https://user-images.githubusercontent.com/108342742/230719651-b997b141-eb12-4aea-ac56-970ca690fcc6.png)

**Comment by vibhansa-msft** [comment]
You account is HNS enabled, kindly add "--use-adls=true" to your command line options and retry,

**Comment by danilo-santoro** [comment]
Hello @vibhansa-msft,

I already tried the Azure Data Lake Storage flag and it seems to work fine for standalone blobfuse2 command on ubuntu box but to be completely ignored as Storage Class in a k8s cluster 1.25.5. My storage class is defined as follows:

`allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-fuse
mountOptions:
- -o allow_other
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --file-cache-timeout-in-seconds=120
- --cancel-list-on-mount-seconds=10
- --log-level=LOG_WARNING
- --use-attr-cache=true
- --cache-size-mb=1000
- --use-adls=true
parameters:
  skuName: Premium_LRS
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
`

**Comment by danilo-santoro** [comment]
@vibhansa-msft I think I succeeded, but in a strange way. It seems that defining mounting options at Storage Class level is not enough, I had to do the same at PersistentVolume level in this way:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: ref-d8-data-migration
    meta.helm.sh/release-namespace: ref-d8-helm
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  creationTimestamp: "2023-04-11T09:55:45Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ref-d8-datamigration-pv
  resourceVersion: "4794822"
  uid: dcb2c441-8517-4cf1-8667-505da816d40c
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 15Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datamigration-pvc
    namespace: ref-d8
    resourceVersion: "4794819"
    uid: 9ee7a4b4-0236-4d0c-80b6-218dd78d8201
  csi:
    driver: blob.csi.azure.com
    nodeStageSecretRef:
      name: datamigration-secret
      namespace: ref-d8
    volumeAttributes:
      containerName: ct-sadmrndlotdrawd8
      resourceGroup: sadmrndlotdrawd8
      storageAccount: sadmrndlotdrawd8
    volumeHandle: ref-d8-datamigration-pv
  mountOptions:
  - --file-cache-timeout-in-seconds=120
  - --use-adls=true
  - -o allow_other
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blob-fuse
  volumeMode: Filesystem
status:
  phase: Bound
```

Is that the attended behavior?

**Comment by andyzhangx** [comment]
@danilo-santoro if you set `--use-adls=true` in sc mountOptions in the beginning, new PV would have that mount options, it should work; while since your pv is already created, you should append `--use-adls=true` mountOptions on existing pv

**Comment by vibhansa-msft** [comment]
@danilo-santoro : kindly confirm if the above info helps. Close this issue if you are able to mount successfully for gen2 account.

**Comment by danilo-santoro** [comment]
hello @vibhansa-msft, I was able to correctly mount storage account on a 1.25.6 cluster. I'm still a little bit puzzled by @andyzhangx answer, I was supposed that StorageClass were useful also to define mounting points option at PV level ... but if this is the attended behavior I'm ok with that.

**Comment by andyzhangx** [comment]
> hello @vibhansa-msft, I was able to correctly mount storage account on a 1.25.6 cluster. I'm still a little bit puzzled by @andyzhangx answer, I was supposed that StorageClass were useful also to define mounting points option at PV level ... but if this is the attended behavior I'm ok with that.

@danilo-santoro it works if you define mountOptions in sc, and then create new pvc, the k8s would create new pv with updated mountOptions, in your case, pv is already created, then you need to update  mountOptions  of pv manually.

**Comment by danilo-santoro** [comment]
mmm, I defined the storageClass attribute pointing to the created StorageClass in PV in this way:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: ref-d8-data-migration
    meta.helm.sh/release-namespace: ref-d8-helm
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ref-d8-datamigration-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 15Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datamigration-pvc
    namespace: ref-d8
  csi:
    driver: blob.csi.azure.com
    nodeStageSecretRef:
      name: datamigration-secret
      namespace: ref-d8
    volumeAttributes:
      containerName: ct-sadmrndlotdrawd8
      resourceGroup: sadmrndlotdrawd8
      storageAccount: sadmrndlotdrawd8
    volumeHandle: ref-d8-datamigration-pv
  mountOptions:
  - --file-cache-timeout-in-seconds=120
  - --use-adls=true
  - -o allow_other
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blob-fuse
  volumeMode: Filesystem
status:
  phase: Bound
```

It should to avoid that ... am I wrong?
