### ISSUE TITLE
"Input/Output Error" when reading multiple files

### ISSUE THREAD

**Issue by malu-alphabot** [Azure/azure-storage-fuse#1110]
### Which version of blobfuse was used?
2.0.2

### Which OS distribution and version are you using?
Ubuntu 20.04.6 LTS

### If relevant, please share your mount command.

```
allow-other: false
logging:
  level: log_debug
  file-path: "$BLOBFUSE_HOME/$container/blobfuse2.log"
  type: base
  track-time: true
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage
libfuse:
  attribute-expiration-sec: 20
  entry-expiration-sec: 30
  negative-entry-expiration-sec: 0
  fuse-trace: true
file_cache:
  policy: lfu
  path: $BLOBFUSE_HOME/$container/$cachedisk/blobfusetmp
  timeout-sec: 1296000
  max-eviction: 3
  high-threshold: 90
  low-threshold: 60
  max-size-mb: 40000
  cleanup-on-start: true
  policy-trace: true
attr_cache:
  timeout-sec: 30
azstorage:
  type: adls
  endpoint: https://$storage.blob.core.windows.net/
  account-name: $storage
  mode: key
  account-key: $key
  container: $container
  fail-unsupported-op: true
  validate-md5: true
  sdk-trace: true
```
### What was the issue encountered?
When trying to download thirteen files of approximately 1.5GB each in parallel I get the error "Input/output error". Analyzing the log I realized that normally the error is associated with a "Connection reset by peer" message.

Some important information:
- This error only happens when reading data using blobfuse in a local cluster.
- The cluster is located in Brazil and the storage in the East US region.
- On Azure Virtual Machines that are in the same region as the storage we don't get this error for the same conditions.
- The error also happens when we read multiple files sequentially.

### Have you found a mitigation/solution?
No.

### Please share logs if available.
The error log is attached.

[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/11215935/blobfuse2.log)

**Comment by malu-alphabot** [comment]
The error always happens at the end of downloading the files.

**Comment by vibhansa-msft** [comment]
I was looking at your log files and I see this:
" BlockBlob::ReadToFile : Failed to download blob file16.out [read tcp 192.168.0.112:54064->52.239.221.4:443: read: connection reset by peer]"
As you have mentioned earlier there is some connection error coming here. Can you validate downloading of a blob through curl or some other means just to ensure that there is no issue at the network level.

**Comment by vibhansa-msft** [comment]
Are you still hitting the issue ?

**Comment by LakshyAAAgrawal** [comment]
Hey!

I am also facing similar issues. I have a file X in blob storage, which is accessible, but occasionally, it fails to read with input/output error. On investigating the log, I found the following:
```
Apr 21 04:32:42 <MachineName> blobfuse2[8073]: LOG_ERR [block_blob.go (688)]: BlockBlob::ReadToFile : Failed to download blob <path/to/file/in/blob/filename.json> [read tcp ip1:port1->ip2:port2: read: connection reset by peer]
Apr 21 04:32:42 <MachineName> blobfuse2[8073]: LOG_ERR [file_cache.go (840)]: FileCache::OpenFile : error downloading file from storage <path/to/file/in/blob/filename.json> [read tcp ip1:port1->ip2:port2: read: connection reset by peer]
Apr 21 04:32:42 <MachineName> blobfuse2[8073]: LOG_ERR [libfuse_handler.go (647)]: Libfuse::libfuse_open : Failed to open <path/to/file/in/blob/filename.json> [read tcp ip1:port1->ip2:port2: read: connection reset by peer]
```

Could you please suggest what configurations can I use to avoid this issue?
My current configuration
```
logging:
    type: syslog
azstorage:
    account-name: <>
    sas: <>
    endpoint: <>
    container: <>
    update-md5: false
    validate-md5: false
    virtual-directory: true
    
components:
    - libfuse
    - file_cache
    - azstorage
attr_cache:
    timeout-sec: 240
libfuse:
    entry-expiration-sec: 240
file_cache:
    path: /scratch/ramdisk/blobfuse2tmp
```
