### ISSUE TITLE
Relative paths are not working in config file

### ISSUE THREAD

**Issue by kostinalexey** [Azure/azure-storage-fuse#1116]
### Which version of blobfuse was used?
v2

### Which OS distribution and version are you using?
ubuntu 20.04 (WSL2)

### If relevant, please share your mount command.
blobfuse2 mount data --config-file conf1.yaml

```
attr_cache:
  timeout-sec: 7200
azstorage:
  account-name: ***
  container: ***
  endpoint: https://***
  mode: key
  sdk-trace: true
  type: adls
  update-md5: false
  validate-md5: false
  virtual-directory: false
components:
- libfuse
- file_cache
- attr_cache
- azstorage
file_cache:
  max-size-mb: 4096
  path: ./cache
  timeout-sec: 120
libfuse:
  attribute-expiration-sec: 240
  entry-expiration-sec: 240
  negative-entry-expiration-sec: 120
logging:
  file-path: /***
  level: log_info
  type: base
read-only: false
```

### What was the issue encountered?
If relative path is used in cache path then mount half-working. I can see container is mounted and can see files in the container. But it is not possible to read files because cache is not working.

BTW the cache directory is created correctly by blobfuse even with relative path in conf file.

### Have you found a mitigation/solution?
Use absolute paths

### Please share logs if available.
```
Fri Apr 21 12:34:34 BST 2023 : blobfuse2[24709] : LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exit status 1]
Fri Apr 21 12:34:35 BST 2023 : blobfuse2[24709] : LOG_ERR [file_cache.go (806)]: FileCache::OpenFile : error creating directory structure for file ******* [mkdir cache: permission denied]
Fri Apr 21 12:34:35 BST 2023 : blobfuse2[24709] : LOG_ERR [libfuse_handler.go (647)]: Libfuse::libfuse_open : Failed to open ******* [mkdir cache: permission denied]
Fri Apr 21 12:34:35 BST 2023 : blobfuse2[24709] : LOG_ERR [file_cache.go (806)]: FileCache::OpenFile : error creating directory structure for file ******* [mkdir cache: permission denied]
Fri Apr 21 12:34:35 BST 2023 : blobfuse2[24709] : LOG_ERR [libfuse_handler.go (647)]: Libfuse::libfuse_open : Failed to open ******** [mkdir cache: permission denied]
Fri Apr 21 12:34:36 BST 2023 : blobfuse2[24709] : LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exit status 1]
Fri Apr 21 12:34:36 BST 2023 : blobfuse2[24709] : LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exit status 1]
Fri Apr 21 12:34:36 BST 2023 : blobfuse2[24709] : LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exit status 1]
Fri Apr 21 12:34:36 BST 2023 : blobfuse2[24709] : LOG_ERR [cache_policy.go (96)]: cachePolicy::getCacheUsage : error running du [exit status 1]
```
