### ISSUE TITLE
Mount through docker container on host system

### ISSUE THREAD

**Issue by FrsECM** [Azure/azure-storage-fuse#1129]
### Which version of blobfuse was used?
Blobfuse2

### Which OS distribution and version are you using?
Ubuntu22.04 (host)
Ubuntu22.04 (container)

### If relevant, please share your mount command.
Here is a base image i created with blobfuse installed.
The name of this image is **blobfuse2**
```
FROM amd64/ubuntu:22.04
RUN apt update
RUN apt install -y wget

# We install Microsoft packages Repository
RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt update

# We install blobfuse
RUN apt install -y libfuse3-dev fuse3 \
    && apt install -y blobfuse2 tree
```

I created a subimage containing a configuration file : 
```
FROM blobfuse2:latest
COPY config/ config/
RUN mkdir /tmp/.azcache && mkdir /mnt/azmnt
RUN echo "user_allow_other" >> /etc/fuse.conf
RUN echo "blobfuse2 mount all /mnt/azmnt/ --config-file=config/diffusion_data.yaml --ignore-open-flags --foreground=true" >> run.sh
# No longer need tail -F /dev/null because of foreground option 
CMD ["sh","-c","sh run.sh"]
```
I run this docker-compose in order to launch my image : 
```
version: "3.9"
services:
  diffusion_data:
    build:
      context: .
      dockerfile: dockerfile.diffusion_data
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices: 
      - /dev/fuse:dev/fuse
    volumes:
      - /mnt/dockerfuse:/mnt/azmnt
```
As you can see, **/mnt/dockerfuse** on host should contain containers content.
 
### What was the issue encountered?
If i open a terminal in the container, i see that my data are available : 
![image](https://user-images.githubusercontent.com/26071804/235535344-819b8935-ebcc-4b75-9275-8e01abf77398.png)

The problem is that i don't see any file in **/mnt/dockerfuse** on host.
![image](https://user-images.githubusercontent.com/26071804/235535592-3e8ae6bf-23d3-4f7f-80b8-466998e4bc2f.png)

### Have you found a mitigation/solution?
I don't have any solution for the moment. I'am trying this configuration because i consider buying an AppleSilicon computer and i need a workarround in order to mount data in Azureblobstorage on such machine and i thought about containers. I think unified memory is a real plus in order to debug code that won't fit on affordable GPUs and it's better to debug before running cloud pipelines. That's where blobfuse comes in, it's a way to create an env similar to what the cloud job will see.

Thanks for your help !
