### ISSUE TITLE
Support for fnctl locks?

### ISSUE THREAD

**Issue by schwichti** [Azure/azure-storage-fuse#1137]
### Which version of blobfuse was used?
That one from AKS 1.24.10

### Which OS distribution and version are you using?
Ubuntu 22.04.2 LTS

### If relevant, please share your mount command.
```yaml
apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: pvc-blob
      persistentVolumeClaim:
        claimName: pvc-blob
  containers:
    - name: minio
      volumeMounts:
        - name: pvc-blob
          mountPath: /data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 100Gi # While the Kubernetes API capacity attribute is mandatory, this value isn't used by the Azure Blob storage CSI driver because you can flexibly write data until you reach your storage account's capacity limit.
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: {{ .Values.global.simphera.minio.volumeHandle }}
    volumeAttributes:
      resourceGroup: {{ .Values.global.simphera.minio.resourceGroup }}
      containerName: {{ .Values.global.simphera.minio.containerName }}
      storageAccount: {{ .Values.global.simphera.minio.storageAccount }}
      AzureStorageAuthType: MSI
      AzureStorageIdentityClientID: {{ .Values.global.simphera.minio.AzureStorageIdentityClientID }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-blob
  storageClassName: azureblob-fuse-premium
```

### What was the issue encountered?

I am using Azure Blobfuse in a pod that runs MinIO. When I try to import demo data I get the message 
```
mc: <ERROR> Failed to copy `/demos/generated/default/minio/Demo/Results/Passed/results.zip`. We encountered an internal error, please try again.: cause(open /data/.minio.sys/multipart/fa997b18a80d64902f173fbb1be0568f721dab75c46483b82bcb803b09bf1596/f8b564e0-ba77-4cb7-a881-7f58b5d76974/fs.json: operation not permitted) 
```
This error has been discussed here: https://github.com/minio/minio/issues/13185 although a different setup was used. 
However, I read the note that [MinIO won't work when the backend does not support fnctl locks](https://github.com/minio/minio/issues/13185#issuecomment-917007841). This leads me to my final question:
**Does Azure Blobfuse support fnctl locks?**
