### ISSUE TITLE
Add Environment Variable compatiblity with blobfuse Configuration

### ISSUE THREAD

**Issue by FrsECM** [Azure/azure-storage-fuse#1144]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
WSL / Ubuntu20.04

### What was the issue encountered?
I would like to be able to store the account key as an environment variable and use a configuration file at the same time.
The idea is to be able to share the yaml config file but without it's secret.
How can we do this ?

For example :
```yaml
azstorage:
  type: block
  # Enable virtual directory => Important to discover well files
  virtual-directory : true
  account-name: storage_name
  endpoint: https://storage_name.blob.core.windows.net
  # mode possible : key|sas|spn|msi
  mode: key
  account-key: ${VAR:account_key}
```
Or another example : 
```bash
sudo blobfuse2 mount all /media/sy2_data/ --config-file=data/config/sy2_data.yaml --account-key=$ACCOUNT_KEY
```

None of the solution above are working but it would be very interesting because for the moment we can't share blobfuse configuration in our git repos because .
Maybe it's just a lack of knowledge from my side.

### Have you found a mitigation/solution?
No
