### ISSUE TITLE
Can't find logs from Health Monitor

### ISSUE THREAD

**Issue by bnapora** [Azure/azure-storage-fuse#1148]
### Which version of blobfuse was used?
2.0.3

### Which OS distribution and version are you using?
[Debian GNU/Linux 11 (bullseye)]

### If relevant, please share your mount command.
blobfuse2 mount /WSI/az_wsiarchive01/poc1 --config-file=/usr/share/blobfuse2/config.yaml  --ignore-open-flags --foreground=true

### What was the issue encountered?
No health monitor logs created, or at least can't find them. I've searched OS for any logs starting with "monitor..." but none located.

### Have you found a mitigation/solution?
No

### Please share logs if available.
I've attached blobfuse2.log 
[blobfuse2.log](https://github.com/Azure/azure-storage-fuse/files/11514839/blobfuse2.log)

Config file is below:
```
allow-other: true

logging:
  type: syslog
  level: log_debug        # log_off|log_crit|log_err|log_warning|log_info|log_trace|log_debug <log level. Default - log_warning>
  file-path: '/usr/share/blobfuse2/logs/blobfuse2.log'
  max-file-size-mb: 200
  track-time: true        # Change to false after validation

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 500
  negative-entry-expiration-sec: 240

file_cache:
  path: /tmp/blobfuse_cache
  policy: lru                 # lru (least recently used)|lfu (least frequently used)
  timeout-sec: 86400
  max-size-mb: 200
  allow-non-empty-temp: true
  cleanup-on-start: false     # Default=true (determine if yields dirty writes)
  policy-trace: true          # Change to false after validation

attr_cache:
  timeout-sec: 7200

health_monitors:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /usr/share/blobfuse2/logs/
  monitor-disable-list:
    - memory_profiler
```
