### ISSUE TITLE
Help on optimizing Blobfuse2 Settings for read-only image file access

### ISSUE THREAD

**Issue by bnapora** [Azure/azure-storage-fuse#1152]
### Which version of blobfuse was used?
Starting Blobfuse2 Mount : 2.0.3 

### Which OS distribution and version are you using?
[Debian GNU/Linux 11 (bullseye)]

### What was the issue encountered?
We are testing blobfuse for use in an application that displays large image files stored in Azure Blob Container.  (We are also using Blobfuse2 for initial upload of images to Blob Container.) The images do not change once they are uploaded to the Blob Container.  All application access to images is read only.  We are using Blobfuse2 "FileCache".  

In looking at the log file, I see a number of "Need to re-download" messages.  
`LOG_INFO [file_cache.go (794)]: FileCache::OpenFile : Need to re-download _batch01/00443E97-11A0-46E5-9D3E-88578CAD2135.ndpi, but skipping as handle is already open`

Does this indicate that processing or network bandwidth is being utilized to "re-download" the image?  Is there a setting that will disable this type of check?

Also...in general can you provide recommendations on blobfuse2 settings that would optimize performance if "write" integrity is not a requirement?

I'm attaching our current configuration settings below.  Any help is greatly appreciated.

Config.yaml

```
allow-other: true
read-only: false

logging:
  type: syslog
  level: log_trace        # log_off|log_crit|log_err|log_warning|log_info|log_trace|log_debug <log level. Default - log_warning>
  file-path: '/usr/share/blobfuse2/logs/blobfuse2.log'
  max-file-size-mb: 100
  file-count: 10
  track-time: true        # Change to false after validation

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 500
  fuse-trace: true  # Set to false after validation
  negative-entry-expiration-sec: 240
  ignore-open-flags: true

file_cache:
  path: /tmp/blobfuse2_cache
  policy: lru                 # lru (least recently used)|lfu (least frequently used)
  timeout-sec: 604800  # Set for 7 days
  max-size-mb: 200000
  high-threshold: 85
  allow-non-empty-temp: true
  cleanup-on-start: false     # Default=true (determine if yields dirty writes)
  policy-trace: true          # Change to false after validation
  sync-to-flush: false
  offload-io: false

attr_cache:
  timeout-sec: 7200

health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /usr/share/blobfuse2/logs/
  monitor-disable-list:
```
