### ISSUE TITLE
ADLS Blobfuse2 SPN Token generated with wrong resource/audience, auth-resource in config not registered

### ISSUE THREAD

**Issue by red324** [Azure/azure-storage-fuse#1156]
### Which version of blobfuse was used?

blobfuse2 version 2.0.3

### Which OS distribution and version are you using?

Tested with Ubuntu 20.04.4 LTS and Ubuntu 22.04

### If relevant, please share your mount command.

sudo blobfuse2 mount mycontainer --tmp-path=tmp --config-file=config.yml

### What was the issue encountered?

I am getting authorization issues when using blobfuse2 and adls.

My config file (config.yml) is as follows:

``` yml
allow-other: true
 
logging:
  type: base
  level: log_debug
  file-path: ~/blobfuse.log

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage
 
libfuse:
  default-permission: 0777
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
 
azstorage:
  type: adls
  account-name: <account_name>
  mode: spn
  container: <container_name>
  # service principal authentication
  tenantid: <tenant_id>
  clientid: <client_id>
  clientsecret: <client_secret>
  auth-resource: https://storage.azure.com
```

The mounting seems to succeed, but when I try to get to a directory in the file system and list the contents, I receive the error:

`ls: reading directory '.': Input/output error`

Looking at the blobfuse logs, I see:
![image](https://github.com/Azure/azure-storage-fuse/assets/54178966/479f82ef-fe63-40d5-8a7a-e52026aca19b)
> Note: The Authorization is redacted so I am just guessing as to which token is being used based on the results

Earlier in the logs, I can see the tokens that are being created. The token for the blob service uri `https://xxx.blob.core.windows.net/`works when using postman to make calls to the directory. The token generated using the .dfs.core.windows.net does NOT work and produces this error. When I generate a token with: `https://storage.azure.com` as the resource, I am also able to successfully make the API call.

Taking the tokens directly from the blobfuse logs.. I can authenticate properly with the .blob.core.windows.net token:
![image](https://github.com/Azure/azure-storage-fuse/assets/54178966/fe3d25cd-2227-4ec7-924c-389e94676b1e)
![image](https://github.com/Azure/azure-storage-fuse/assets/54178966/1d4ff114-8d06-42c0-8146-1c98f4a13670)

but not the .dfs.core.windows.net token:
![image](https://github.com/Azure/azure-storage-fuse/assets/54178966/318f5d20-aa51-409e-9972-1fb7a440f056)
![image](https://github.com/Azure/azure-storage-fuse/assets/54178966/7043f14f-92fb-4792-9b85-8fd0d345cad1)

My service principal has Reader RBAC access to the Storage Account, and has R-X ACL access to container and RWX access on the directory I am trying to `ls` in. It is not possible to grant further RBAC access due to the way access partitioning is set up in the organization's data lake, so we use ACLs for authorization. I am able to `ls` on the container, but not on the directory underneath the container, I am also able to `cd` into the directory from the container.

According to the way ACLs vs. RBAC work in the Data Lake, it would appear that I should not need the `storage blob data contributor` role since I have `r-x` access at container and `rwx` at the directory level: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-access-control-model#how-permissions-are-evaluated

I have tested mounting this same storage container using `blobfuse` version 1 and it does work as expected. I checked the token it is using and the resource appears to be: `https://storage.azure.com`.

So I tried to set the `auth-resource` in the config file for `blobfuse2` to equal `https://storage.azure.com` so that the correct token will be generated and used, but I am still receiving access issues shown above.

I am unsure of how to 100% confirm the token that is being used for the GET call since the token is redacted, but it would seem to me that regardless of what I set as the auth-resource, it is using the https://xxx.dfs.core.windows.net endpoint since I am getting permission errors. 

Conclusion: 

The proper token auth resources appear to be either `https://storage.azure.com` or `https://<account>.blob.core.windows.net` as stated here: https://learn.microsoft.com/en-us/azure/storage/blobs/authorize-access-azure-active-directory#microsoft-authentication-library-msal and here: https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#use-oauth-access-tokens-for-authentication

I think there is a bug in V2 where the token is being generated with the `https://account_name.dfs.core.windows.net` uri as the audience/resource (and/or also not taking into account the `auth-resource` in the config file)

### Have you found a mitigation/solution?

No

### Please share logs if available.

See screen shots above. I can share more as needed.

This is a follow up from discussion: https://github.com/Azure/azure-storage-fuse/discussions/1153
