### ISSUE TITLE
Unable to list directories, create files, write files in the blobfuse2 mounted container with RHEL 7.7 and RHEL 8.x. Same works in Ubuntu 20.04

### ISSUE THREAD

**Issue by Lddeiva** [Azure/azure-storage-fuse#1157]
### Which version of blobfuse was used?
blobfuse2

### Which OS distribution and version are you using?
Tried with RHEL 7.7 and 8.x

### What was the issue encountered?
Unable to list directories, create files, write files in the blobfuse2 mounted container with RHEL 7.7 and RHEL 8.x. Same works in Ubuntu 20.04

### Have you found a mitigation/solution?
No.

### Please share logs if available.

touch mycontainer/V001/test2.txt
touch: cannot touch 'mycontainer/V001/test2.txt': Input/output error

cp test3.txt mycontainer/V001/
cp: cannot create regular file 'mycontainer/V001/': Not a directory

ls -l mycontainer/V001
total 0
-rw-r----- 1 root root      0 May 26 09:08 test2.txt
-rw-r----- 1 root root      0 May 25 09:47 test.txt
[root@server ~]# ls -l mycontainer/V001
ls: cannot open directory 'mycontainer/V001': No such file or directory

**Comment by Lddeiva** [comment]
The response from list directories/files operation is inconsistent as seen above.

**Comment by Lddeiva** [comment]
![image](https://github.com/Azure/azure-storage-fuse/assets/61077834/ac45ed3c-0ce6-4b00-95a1-96269428f6bf)

**Comment by souravgupta-msft** [comment]
@Lddeiva, kindly share the following.

1. blobfuse2 version used
2. blobfuse2 mount command
3. Config file
4. blobfuse2 logs

**Comment by Lddeiva** [comment]
Thank you, @souravgupta-msft 💚. The issue was resolved after we changed the endpoint from `blob` to `dfs`.

> We use ADLS Gen2 storage account which has hierarchical namespace enabled. So, the `blob` endpoint didn't work and caused issues.

```yaml
endpoint: https://mystorage00371.blob.core.windows.net/
```

When we changed the endpoint to `dfs`, it worked fine.

```yaml
endpoint: https://mystorage00371.dfs.core.windows.net/
```


For others referring this issue later, please find the working **config.yaml** for blobfuse2 to be used against an ADLS Gen2 storage account. This is a sample and you need to refer the documentation https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-how-to-deploy for up-to-date information.

```yaml
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 8
  blocks-per-file: 3
  cache-size-mb: 1024

azstorage:
  type: adls
  account-name: mystorage00371
  container: containername
  subdirectory: dir1/app/meow
  endpoint: https://mystorage00371.dfs.core.windows.net/
  mode: key
  account-key: *************************************************
  sdk-trace: false
```
