### ISSUE TITLE
file stuck in cache

### ISSUE THREAD

**Issue by ggrrll** [Azure/azure-storage-fuse#1195]
### Which version of blobfuse was used?
2.0.4

### Which OS distribution and version are you using?
Ubuntu 20.04.6 LTS

### What was the issue encountered?
file does not sync downstream : the new v. fetched from remote server, gets stuck into cache  (also beyond timeout)

**Comment by vibhansa-msft** [comment]
Kindly share little more details on your workflow and what issue you have observed ? 
Files once downloaded will be there in local disk-cache untill timeout. Post timeout if any handle to that file is open, Blobfuse will not evict them. Kindly ensure your application closes the file-handle after it is done with processing.

**Comment by ggrrll** [comment]
hey, 

thanks for your answer
I am not using any application (just terminal)

new file can is pull locally immediately , but changes are stuck in the cache folder

is there a specific flag controlling that? 

thanks

**Comment by vibhansa-msft** [comment]
What do you mean by "changes are stuck in cache folder". I assume what you refer here is changes are present in local cache but not updated on container. This means the file handle was not closed from your end. If you enable log_debug you can see whether a close call was received by blobfuse or not. If received whether there was any sort of failure or not.

**Comment by ggrrll** [comment]
hey, 

no, I meant the opposite (as I mentioned in the beginning , it's about downstream sync)

**Comment by ggrrll** [comment]
also, I have another (maybe related) issues  (should I open a new GH issue? ) 

the `blobfuse2` command keeps running at 100% CPU

**Comment by ggrrll** [comment]
```
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 0
  entry-expiration-sec: 0
  negative-entry-expiration-sec: 0

file_cache:
  path: /tmp/blob_cache
  timeout-sec: 0
  max-size-mb: 4096

attr_cache:
  timeout-sec: 20
```

still no downstream sync
