### ISSUE TITLE
MSI System assigned - Server failed to authenticate the request

### ISSUE THREAD

**Issue by guigui43** [Azure/azure-storage-fuse#1198]
### Which version of blobfuse was used?
2.0.4
Roles are OK between Storage Blob Data Reader and VM

### Which OS distribution and version are you using?
CentOS Linux release 7.9.2009

### What was the issue encountered?
Status: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header

### Context
We have several blobfuse2 mount points on the same VM to different resource groups and different blobstorage types (StorageV2 with ADLS Gen2 or StorageV2).

All are impacted

Configuration is well set:
- block if StorageV2
- adsl if ADLS Gen2

We have lost connections and input/output error issue
When we look at the logs it indicates a token issue. 
Whereas normally it is managed by the Azure Control Plane and MSI

### Have you found a mitigation/solution?
No

### Please share logs if available.
```yaml
azstorage:
    type: adls
    account-name: xxxxxxxxxxxxxxxxxxxxxxx
    endpoint: https://xxxxxxxxx.blob.core.windows.net
    mode: msi
    container: xxx-inbox
    update-md5: false
    validate-md5: false
    virtual-directory: true
file_cache:
    allow-non-empty-temp: true
    cleanup-on-start: true
components:
    - libfuse
    - file_cache
    - azstorage
```

```bash
Jul 12 10:50:12 lnx000xxx blobfuse2[28379]: 2023/07/12 10:50:12 ==> REQUEST/RESPONSE (Try=1/14.297966ms, OpTime=14.428267ms) -- RESPONSE STATUS CODE ERROR#012   GET https://ixxxgbl1sa01.blob.core.windows.net/imifgbl1?comp=list&delimiter=%2F&include=metadata&maxresults=2&prefix=envoi&restype=container&timeout=901#012   Authorization: REDACTED#012   User-Agent: [Azure-Storage-Fuse/2.0.4 (CentOS Linux 7 (Core)) Azure-Storage/0.15 (go1.20.5; linux)]#012   X-Ms-Client-Request-Id: [a2e6b121-f234-4204-675e-6a5c81661d80]#012   X-Ms-Version: [2020-10-02]#012   --------------------------------------------------------------------------------#012   RESPONSE Status: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.#012   Content-Length: [404]#012   Content-Type: [application/xml]#012   Date: [Wed, 12 Jul 2023 08:50:12 GMT]#012   Server: [Microsoft-HTTPAPI/2.0]#012   Www-Authenticate: [Bearer authorization_uri=https://login.microsoftonline.com/658ba197-6c73-4fea-91bd-1c7d8de6bf2c/oauth2/authorize resource_id=https://storage.azure.com]#012   X-Ms-Error-Code: [InvalidAuthenticationInfo]#012   X-Ms-Request-Id: [c9a70320-c01e-0057-189d-b44a51000000]#012Response Details: <feff><Code>InvalidAuthenticationInfo</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header. </Message><AuthenticationErrorDetail>Lifetime validation failed. The token is expired.</AuthenticationErrorDetail>
```
