### ISSUE TITLE
Blobfuse files do not sync after mounting in a container

### ISSUE THREAD

**Issue by robinatmicrosoft** [Azure/azure-storage-fuse#1202]
### Which version of blobfuse was used?
blobfuse2=2.0.4, blobfuse=1.4.1

### Which OS distribution and version are you using?
Ubuntu 20.04.4 LTS

### What was the issue encountered?
Files are sometimes not syncing despite setting --timeout-sec=0 and --direct-io=true. 

### Have you found a mitigation/solution?
Manually dropping the kernel cache with `sysctl -w vm.drop_caches=3` seems to work, but I may not always have write access to /proc/sys file system, so this isn't a long term solution.

**Comment by vibhansa-msft** [comment]
ICM : 401293448
As kernel page cache cleanup works and direct_io does not, it means kernel is not honoring the direct_io flag in this case.
We have observed off late that in containerized mounts this issue is hit. Is this the same case here as well ?

**Comment by souravgupta-msft** [comment]
@robinatmicrosoft, can you please share your mount command and config file used.
Also, to enable direct_io, you will have to pass `-o direct_io` in your mount command instead of `--direct-io=true`.

**Comment by souravgupta-msft** [comment]
The libfuse and file_cache components need correction. The `direct-io` and `timeout-sec` fields are not set correctly. You can refer [this config](https://github.com/Azure/azure-storage-fuse/blob/main/testdata/config/azure_key_directio.yaml) as reference.

```
libfuse:
    attribute-expiration-sec: 0
    entry-expiration-sec: 0
    negative-entry-expiration-sec: 0
    direct-io: true
file_cache:
    path: /scratch/INPUT1_tmp
    max-size-mb: 163840
    timeout-sec: 0
```

Kindly retry after making the above change.
