### ISSUE TITLE
File size and content not updated correctly when overwriting with shorter data

### ISSUE THREAD

**Issue by yozik04** [Azure/azure-storage-fuse#1209]
### Which version of blobfuse was used?
2.0.2

### Which OS distribution and version are you using?
Debian 11 bullseye

### If relevant, please share your mount command.
`/usr/bin/blobfuse2 mount /mnt/test --config-file=/usr/local/etc/blobfuse2-test.yaml`

Configuration (contents of `/usr/local/etc/blobfuse2-test.yaml`):
```yaml
components:
  - libfuse
  - azstorage
foreground: true
libfuse:
  default-permission: 0644
  disable-writeback-cache: true
logging:
  level: log_warning
  type: syslog
azstorage:
  container: test
  mode: msi
  account-name: xxx
  appid: xxx
  endpoint: https://xxx.blob.core.windows.net
```

### What was the issue encountered?

When editing a file in the mounted directory, the file size does not change if the new content is shorter than the original one. The file also retains the old data after the overwritten bytes, resulting in incorrect and inconsistent content.

For example, if I create a file with 9 bytes and then overwrite it with 1 byte, the file still shows 9 bytes and the remaining 8 bytes are from the old content.

```bash
cd /mnt/test
echo -n '123456789' > test.txt
echo -n '0' > test.txt
cat test.txt
023456789
```

### Have you found a mitigation/solution?
No

### Please share logs if available.
The logs do not show any errors or warnings related to this issue.

**Comment by vibhansa-msft** [comment]
I see that your config is invalid. 

components:
    - libfuse
    - file_cache
    - attr_cache
    - azstorage

Also, provide config for file-cache. Without file-cache or streaming component in pipeline all your write requests will be sent to storage container and it will end up overwriting the existing file. You can refer to some of the sample config files that we have in our root folder.

**Comment by yozik04** [comment]
@vibhansa-msft That is the problem that we did not want any cache.

We need every read/write to end up with the query to the storage because files can be changed both remotely and locally.

**Comment by vibhansa-msft** [comment]
For that as well you will need atleast streaming component with no config of buffers so that every write is upstreamed.

**Comment by yozik04** [comment]
Unfortunately this does not work as well...

Configuration:
```
components:
  - libfuse
  - stream
  - azstorage
foreground: true
libfuse:
  default-permission: 0644
  disable-writeback-cache: true
logging:
  level: log_warning
  type: syslog
azstorage:
  container: test
  mode: msi
  account-name: xxx
  appid: xxx
  endpoint: https://xxx.blob.core.windows.net
```

Result is absolutely the same as I described initially.
```
cd /mnt/test
echo -n '123456789' > test.txt
echo -n '0' > test.txt
cat test.txt
023456789
```

**Comment by yozik04** [comment]
Next configuration works for now:
```yaml
components:
  - libfuse
  - file_cache
  - azstorage
foreground: true
libfuse:
  direct-io: true
  default-permission: 0644
  disable-writeback-cache: true
file_cache:
  path: /tmp/blobfuse2-cache
  timeout-sec: 0
logging:
  level: log_warning
  type: syslog
azstorage:
  container: test
  mode: msi
  account-name: xxx
  appid: xxx
  endpoint: https://xxx.blob.core.windows.net
```

Instantly get file syncs both directions.
