### ISSUE TITLE
Listing directory contents is not cached (WSL2)

### ISSUE THREAD

**Issue by natbprice** [Azure/azure-storage-fuse#1245]
### Which version of blobfuse was used?
blobfuse2 2.1.1-preview.1

### Which OS distribution and version are you using?
WSL2 with Ubuntu 22.04.2 LTS

### If relevant, please share your mount command.
`sudo blobfuse2 mount ./MYCONTAINER --config-file=config.yaml`

```
allow-other: true
read-only: true

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage
  
logging:
  type: syslog
  level: log_info
  file-path: ~/blobfuse/logs/log.txt

libfuse:
  attribute-expiration-sec: 86400
  entry-expiration-sec: 86400
  negative-entry-expiration-sec: 86400

file_cache:
  path: ~/blobfuse/cache
  timeout-sec: 86400
  max-size-mb: 4096

attr_cache:
  timeout-sec: 86400
  no-cache-on-list: false

azstorage:
  type: adls
  account-name: MYACCOUNT
  account-key: MYKEY
  endpoint: https://MYACCOUNT.dfs.core.windows.net/
  mode: key
  container: MYCONTAINER

```

### What was the issue encountered?
I have an ADLS Gen2 storage account with a container with many files where each file is in a different subdirectory. Because listing all files is an expensive operation, I would like to recursively list all files/directories upfront and cache the results. However, it appears each list operation is resulting in new calls to `ListFilesystemDir` API. I observe only that the subsequent `GetFileProperties` API calls are not repeated. 

### Have you found a mitigation/solution?
No

### Please share logs if available.
I read the WSL wiki, but it wasn't clear to me how to get logging working with WSL. I monitored the requests at the storage account level.
