### ISSUE TITLE
Block List Invalid ?

### ISSUE THREAD

**Issue by DevopsMercenary** [Azure/azure-storage-fuse#1251]
### Which version of blobfuse was used?

blobfuse2 version 2.1.1-preview.1

### Which OS distribution and version are you using?

Linux blob-host 6.2.0-1012-azure #12~22.04.1-Ubuntu SMP Thu Sep  7 14:07:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### If relevant, please share your mount command.

blobfuse2 mount ~/datadelivery --config-file=./config-lite.yaml

my  `config-lite.yaml`
```
allow-other: false

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: ddeliverylight
  account-key: Is3rymQt4....
  endpoint: https://ddeliverylight.blob.core.windows.net
  mode: key
  container: test
```

### What was the issue encountered?

See Logs attached

The file still copies but very slow.

I disabled the cache but could that be the issue? 

### Have you found a mitigation/solution?

Nope

### Please share logs if available.

https://gist.github.com/DevopsMercenary/627d7b59076c47a329ebdfeaf24f498c
