### ISSUE TITLE
Each container is using 100% CPU

### ISSUE THREAD

**Issue by malu-alphabot** [Azure/azure-storage-fuse#1266]
### Which version of blobfuse was used?
2.0.4

### Which OS distribution and version are you using?
Ubuntu 22.04.1 LTS

### If relevant, please share your mount command.
Below is a part of my config file:

```
allow-other: true
read-only: true
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage
file_cache:
  timeout-sec: 10368000 # 120 days
  max-eviction: 50
  max-size-mb: 300000
  high-threshold: 95
  low-threshold: 75
  cleanup-on-start: true
attr_cache:
  timeout-sec: 10
azstorage:
  type: adls
  max-concurrency: 32
  max-retries: 10000
health_monitor:
  enable-monitoring: true
  output-path: $BLOBFUSE_HOME/$container/healthmonitor
```

We use the .azsec file to mount.

### What was the issue encountered?
I have three containers mounted on my machine, and each of them is using 100% of one core all the time, even when I'm not reading new data

### Have you found a mitigation/solution?
No
This problem is similar to the one reported in the issue #1256 , but in my case I have cache configured to store data for multiple days and even after finishing downloading the files, 100% cpu continues to be used.

### Please share logs if available.
I have healthmonitor activated, I grep the last 10 lines with "CPUUsage" to exemplify the values I'm getting:

```
	"CPUUsage": "100.0%",
	"CPUUsage": "93.3%",
	"CPUUsage": "100.0%",
	"CPUUsage": "100.0%",
	"CPUUsage": "100.0%",
	"CPUUsage": "93.3%",
	"CPUUsage": "100.0%",
	"CPUUsage": "100.0%",
	"CPUUsage": "100.0%",
	"CPUUsage": "100.0%",
```
