### ISSUE TITLE
Can't  see directories directly in containers, only in subdirectories when mounted

### ISSUE THREAD

**Issue by gjstreicher-ims** [Azure/azure-storage-fuse#1284]
### Which version of blobfuse was used?
version 2.1.1

### Which OS distribution and version are you using?
Ubuntu 22.04.3 LTS x86_64

### If relevant, please share your mount command.
```
mkdir -p ./test/cache
mkdir -p ./test/ghij
sudo blobfuse2 mount ./test/ghij --config-file=./azure-sa.yaml --allow-other
```
Config file contents (azure-sa.yaml):
```
# Refer ./setup/baseConfig.yaml for full set of config parameters

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 50
  blocks-per-file: 18
  cache-size-mb: 7168

file_cache:
    path: ./test/cache

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: <ACCOUNT_NAME_HERE>
  account-key: <ACCOUNT_KEY_HERE>
  endpoint: https://<ACCOUNT_NAME_HERE>.blob.core.windows.net
  mode: key
  container: ghij
  subdirectory: asdf
```

### What was the issue encountered?
The blob container is called `ghij` and it contains a directory called `asdf`.

If I leave out the `subdirectory: asdf` key-value pair under `azstorage`, I'm unable to see the `asdf` directory in the `ghij` container. I can only see the files (block blobs) directly stored in the container alongside the 'asdf' directory.

If I include the `subdirectory: asdf`, then I can see both the directories and files (block blobs) inside the `asdf` directory.

Setting the `virtual-directory` property to `true` or `false` has no impact on this issue.

### Have you found a mitigation/solution?
A simple solution would be to always have a single directory inside the container and to always mount it instead of the container, but the container should allow for that behaviour by itself as it does in the Azure Storage Explorer.

### Please share logs if available.
If you can tell me where to find the log files, I'll add the contents here.

**Comment by vibhansa-msft** [comment]
Is it a HNS account that you are mounting?

**Comment by vibhansa-msft** [comment]
If its HNS account, then while mounting using blobfuse you need to supply an extra param that informs blobfuse that you are mounting a HNS enabled account. Without this some of the functionality may not work properly.

**Comment by vibhansa-msft** [comment]
Also, as you are mounting a HNS account you config stand invalid for this.  Refer below snippet and update accordingly.
```
azstorage:
  type: adls
  account-name: <ACCOUNT_NAME_HERE>
  account-key: <ACCOUNT_KEY_HERE>
  endpoint: https://<ACCOUNT_NAME_HERE>.dfs.core.windows.net
  mode: key
  container: ghij
  subdirectory: asdf
```
