### ISSUE TITLE
Multiple container shares with shared config causes cache clashes

### ISSUE THREAD

**Issue by dortamur** [Azure/azure-storage-fuse#1341]
### Which version of blobfuse was used?

blobfuse2 version 2.2.0

### Which OS distribution and version are you using?

Debian 10.13

### If relevant, please share your mount command.

`/etc/fstab`:

blobfuse2 /opt/www/site-alpha/ fuse defaults,_netdev,--config-file=/opt/etc/blobfuse2-sites.yaml,--container-name=site-alpha,direct_io,allow_other,ro,umask=0222 0 0
blobfuse2 /opt/www/site-beta/ fuse defaults,_netdev,--config-file=/opt/etc/blobfuse2-sites.yaml,--container-name=site-beta,direct_io,allow_other,ro,umask=0222 0 0

### What was the issue encountered?

The caching is not taking into consideration the container name in cache path.

I am mounting several containers as separate paths from the same storage account. The only config change per share is the container name.
If I use the same `--config-file` and specify a different container in the mount, then they both use the same cache directory at the top level of the cache directory, rather than having a per-container cache.

That is, if I define:
```yaml
   path: /opt/var/cache/blobfuse2-sites
```
...then I would expect the separate containers to be cached in `/opt/var/cache/blobfuse2-sites/site-alpha/` and `/opt/var/cache/blobfuse2-sites/site-beta/`

As it is, they both write to the same directory and content clashes occur, with content from one site appearing in the other.

### Have you found a mitigation/solution?

I can specify a separate `--tmp-path` or `--block-cache-path` per mount, or I could duplicate config files with different path settings in them.

**Comment by dortamur** [comment]
This is the core of my config `blobfuse2-sites.yaml`:

```yaml
read-only: true
allow-other: true

components:
  - libfuse
#  - file_cache
  - block_cache
  - attr_cache
  - azstorage

libfuse:
  default-permission: 0444
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 120
  disable-writeback-cache: true

attr_cache:
  timeout-sec: 120

block_cache:
  block-size-mb: 1
  mem-size-mb: 128
  path: /opt/var/cache/blobfuse2-sites
  prefetch: 80
  parallelism: 128
  disk-timeout-sec: 120

file_cache:
  path: /opt/var/cache/blobfuse2-sites
  timeout-sec: 120
  max-size-mb: 4096
  cleanup-on-start: true

azstorage:
  account-name: acctname
  mode: sas
  sas: "xxx"
  endpoint: https://acctname.blob.core.windows.net
```

I've tried both `file_cache` and `block_cache`.
