### ISSUE TITLE
How to enable blobfuse2 Health Monitor on AKS Cluster 

### ISSUE THREAD

**Issue by svelama** [Azure/azure-storage-fuse#1356]
### Which version of blobfuse was used?
blobfuse2 version: 2.1.2

### Which OS distribution and version are you using?
AKS 1.28.5

### Current Setup and Application
Dynamically creating Blob SA containers with PV/PVC's, which'll then mounted with pods

Storage Class
```yaml
.......
provisioner: blob.csi.azure.com
parameters:
  protocol: fuse2
  ...
mountOptions:
  ...
```

### What was the issue encountered?
Looking at the docs, it says 

[`Add the following section to your blobfuse2 config file`](https://github.com/Azure/azure-storage-fuse/blob/main/tools/health-monitor/README.md#sample-config) 
```yaml
health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: outputReportsPath
  monitor-disable-list:
    - file_cache_monitor
    - memory_profiler
```

now, as I'm using an AKS cluster that manages the blobfuse2 as a plugin, how do I enable health monitor on AKS cluster, also how to pass a config for file caching? 

### Have you found a mitigation/solution?
No
