### ISSUE TITLE
Read cache does not expire

### ISSUE THREAD

**Issue by lennartack** [Azure/azure-storage-fuse#1363]
### Which version of blobfuse was used?
I'm using managed AKS with Kubernetes 1.27.7

Definitions of the StorageClass, PV, and PVC:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-fuse-standard
allowVolumeExpansion: true
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=120
- --use-attr-cache=true
- --cancel-list-on-mount-seconds=10
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --log-level=LOG_WARNING
- --cache-size-mb=1000
parameters:
  skuName: Standard_LRS
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-log-storage
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-standard
  csi:
    driver: blob.csi.azure.com
    readOnly: true
    volumeHandle: -redacted-#insights-logs-kube-audit-admin
    volumeAttributes:
      resourceGroup: -redacted-
      storageAccount: -redacted-
      containerName: insights-logs-kube-audit-admin
      protocol: fuse2
    nodeStageSecretRef:
      name: audit-log-storage
      namespace: delta10-monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-log-storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: audit-log-storage
  storageClassName: azureblob-fuse-standard
```

### What was the issue encountered?

I'm trying to access logs in a storage account (written by an Azure Monitor diagnostic setting), from within a pod. After a file is accessed the local copy does not change when the file is updated again by Azure Monitor. It seems as if the cache never expires.

For example, here's a file in the pod:
```
# stat PT1H.json 
  File: PT1H.json
  Size: 115301    	Blocks: 0          IO Block: 4096   regular file
Device: 2000d3h/2097363d	Inode: 202         Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-03-13 17:00:43.000000000 +0000
Modify: 2024-03-13 16:01:36.000000000 +0000
Change: 2024-03-13 16:01:36.000000000 +0000
 Birth: -
```

This file is only 552K. The actual file is 135M. The Modify time above is the same as the creation time below (which uses GMT+1):

![Screenshot at 2024-03-13 19-02-30](https://github.com/Azure/azure-storage-fuse/assets/17706115/eae07bf4-0242-46bb-b6ff-d54ad0b2e286)
