### ISSUE TITLE
I want to display the latest BLOB data using streaming method.

### ISSUE THREAD

**Issue by Shunya-Seki** [Azure/azure-storage-fuse#1390]
### Which version of blobfuse was used?
Blobfuse2　version: 2.3.0~preview.1

### Which OS distribution and version are you using?
Rhel8.8

### If relevant, please share your mount command.
◆mount command
blobfuse2 mount /blobmount --config-file=/etc/blobfuse2config.yaml -o allow_other

◆config.yaml
# Refer ./setup/baseConfig.yaml for full set of config parameters

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 0
  entry-expiration-sec: 0
  negative-entry-expiration-sec: 0
  direct-io: true

stream:
  block-size-mb: 0
  max-buffers: 0
  buffer-size-mb: 0

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: xxxxx
  objid: xxxxxxxxx
  endpoint: xxxxxx
  mode: msi
  container: xxxx

### What was the issue encountered?
I want to use the Stream method and ensure that the data in Blob Storage is always up to date on the OS side where the mount is performed.
Is the above configuration okay?
I want to confirm just in case.

### Have you found a mitigation/solution?
The configuration seems to be working fine, and the latest BLOB data is being displayed without any issues.

**Comment by vibhansa-msft** [comment]
If you want to refresh the contents locally as and when they are updated on the container then this configuration will not work. What you need here is to use '-o direct_io' cli parameter. 'stream` is not a stable component so you can migrate to `block-cache` instead. Sample command and config below :

```
blobfuse2 mount /blobmount --config-file=/etc/blobfuse2config.yaml -o allow_other -o direct_io
```
```
logging:
  type: syslog
  level: log_debug

components:
  libfuse
  block_cache
  attr_cache
  azstorage

libfuse:
  attribute-expiration-sec: 0
  entry-expiration-sec: 0
  negative-entry-expiration-sec: 0

block_cache:
  block-size-mb: 8
  mem-size-mb: 2048
  prefetch: 12
  parallelism: 64

attr_cache:
  timeout-sec: 7200

azstorage:
  account-name: xxxxx
  objid: xxxxxxxxx
  mode: msi
  container: xxxx
```
