### ISSUE TITLE
Cannot see files in mounted folder from within a Docker container

### ISSUE THREAD

**Issue by JackCaster** [Azure/azure-storage-fuse#1522]
### Which version of blobfuse was used?
blobfuse2 version 2.3.2

### Which OS distribution and version are you using?
Linux Debian

### If relevant, please share your mount command.
blobfuse2 mount <...> --config-file=.blobfuse2.yml --subdirectory=<...> --tmp-path=<...> 

### What was the issue encountered?
I am working with a Docker container (specifically, a VS Code Dev Container). If I mount the blob before I start the Docker container, then I can see the files in the mounted folder. If I mount the blob after I started the Docker container (from a terminal in the host---not within the Docker), I can only see mounted folder but not the actual files.

### Have you found a mitigation/solution?
No

### Config
```yaml
allow-other: true # adjust also etc/fuse.conf

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: <...>
  container: <...>
  mode: sas # set env variable AZURE_STORAGE_SAS_TOKEN

```
