### ISSUE TITLE
The blob file will not updated  if  reading the same file from the different workload

### ISSUE THREAD

**Issue by zhangchl007** [Azure/azure-storage-fuse#1525]
### Which version of blobfuse was used?

blobfuse2-2.3.0-1
### Which OS distribution and version are you using?
azurelinux

### If relevant, please share your mount command.

the pvc mount by storage class

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-fuse2
provisioner: blob.csi.azure.com
parameters:
  skuName: Premium_LRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS, Standard_ZRS, Premium_ZRS
  protocol: fuse2
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=1
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=1
  - -o attr_timeout=1
  - -o entry_timeout=1
  - -o negative_timeout=120
  - --log-level=LOG_WARNING
  - --cache-size-mb=10000
 
 ```
### What was the issue encountered?

we mount the blobfuse into different pods  with the same pvc in different AKS nodes , one pod will update the data in the file , another pod only read the file, but we find the 

### Have you found a mitigation/solution?

not yet
### Please share logs if available.

![image](https://github.com/user-attachments/assets/f7139fed-1616-4e79-9be1-1d312addec7a)

![image](https://github.com/user-attachments/assets/b5e958b1-0c05-470f-9470-54b40b6f556c)
