### ISSUE TITLE
Question regarding settings for streaming video content (> 20GiB larger)

### ISSUE THREAD

**Issue by calexandre** [Azure/azure-storage-fuse#1540]
Hey all,
I'm trying to configure blobfuse2 for a video streaming application with recording feature and would like optimize it for the following scenario:

- It will handle big streams with 4 to 5 hours long using standard 1080p h264, which means each recorded stream may reach about 20GiB
- Blobfuse2 is mounted on a VM size `Standard F4s v2 (4 vcpus, 8 GiB memory)`
- The storage account is a Premium Storage Account with Block Blob configured.

Currently using the poor man's benchmark tool `dd if=/dev/zero of=/home/azureuser/blobfuse-mount bs=100M count=10 oflag=dsync` I'm getting roughly 115MB/s.

Do you think its possible to squeeze some additional throughput using blobfuse2?

I would love to hear your thoughts on this...

This is the configuration I'm using:

```
allow_other: true

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

stream:
  block-size-mb: 64
  max-buffers: 16
  buffer-size-mb: 128
  file-caching: false

attr_cache:
  max-size-mb: 1024
  timeout-sec: 3600

azstorage:
  type: block
```

**Comment by vibhansa-msft** [comment]
"stream" is not a good option to choose here. Use "block-cache" instead. You can refer our sample block-cache config [here](https://github.com/Azure/azure-storage-fuse/blob/main/sampleBlockCacheConfig.yaml)

**Comment by calexandre** [comment]
> "stream" is not a good option to choose here. Use "block-cache" instead. You can refer our sample block-cache config [here](https://github.com/Azure/azure-storage-fuse/blob/main/sampleBlockCacheConfig.yaml)

Thank you! We implemented block-cache and performance went to 300Mb/s!

**Comment by vibhansa-msft** [comment]
If this is as per your expectations then kindly close this bug here.

**Comment by calexandre** [comment]
sorry @vibhansa-msft , I was expecting some results before deciding to close this issue...

Unfortunately, we're having some consistency problems, due to the large size of the file being written...
This is related to a video recording which may last 4 hours or more. This means that the file being written to is kept open for at least 4 hours or more. Once the stream ends, we're noticing some file consistency issues on after 1-2 hours of playout...

Are there any data consistency options that can be tweaked? I don't mind sacrificing throughput for consistency...

**Comment by vibhansa-msft** [comment]
What kind of consistency issue you are hitting here?
As per your config writing two different files and keeping them open for 4 hours shall not be a problem. If you wish to flush your data in between the stream writing you can call 'flush' call on the open handle as well.

**Comment by vibhansa-msft** [comment]
If you have any specific issue that you are hitting and want us to diagnose that as part of this, feel free to reopen this item.

**Comment by calexandre** [comment]
The consistency/corruption issues I'm dealing with is related to mp4 written directly to a blobfuse mount. These MP4 files are generated as part of a recording feature in a live streaming app (AntMedia Server).

Since this is a third party app, I don't have control over the code or the way it handles files...I just setup the target directory for a recording and that's it.

I'm not even sure its related to blobfuse so I'm trying to eliminate variables...

I got one "strange" result though: So went ahead and tinkered with the configuration and changed some settings to eliminate all sorts of caching by enabling `directio` to bypass the kernel. I was expecting a performance hits as stated in the documentation, but instead I went from 300MB/s to 1.3GiB/s on write throughput performance, which is insane. 

This the config yaml that achived such result:

```yaml
allow-other: true

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - block_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 0
  entry-expiration-sec: 0
  negative-entry-expiration-sec: 0
  disable-writeback-cache: true
  direct-io: true

block_cache:
  block-size-mb: 32
  mem-size-mb: 2048
  prefetch: 40
  #parallelism: 128

attr_cache:
  timeout-sec: 0
  no-symlinks: false

health_monitor:
  enable-monitoring: false
  output-path: /mnt

azstorage:
  type: block
  account-name: spttostglobalstorage
  endpoint: https://spttostglobalstorage.blob.core.windows.net/
  mode: sas
  sas: REDACTED
```

This was a very unexpected result, because I don't even think the storage account can handle that much (although I'm using Premium storage account).

I used the old fashioned `dd` to test performance:

```bash
sudo dd if=/dev/zero of=~/blobfuse-test/test1 bs=200M count=20 oflag=dsync
20+0 records in
20+0 records out
4194304000 bytes (4.2 GB, 3.9 GiB) copied, 3.13689 s, 1.3 GB/s
```

With the above in mind, I would like to try the most conservative settings, even if it cripples my application... Which additional settings can I tinker with to ensure maximum consistency?

(I would like to reopen the issue, but I don't have permissions to do so)
