### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by gakolhe** [Azure/azure-storage-fuse#1551]
I am using blobfuse2 to mount a blobstorage.
The account is standard performance account, and not premium (page) block blob storage.

Below are the commands used to mount.

```
sudo mkdir -p /mnt/resource/blobfusetmp/block_cache
sudo mkdir -p /mnt/resource/blobfusetmp/file_cache
sudo mkdir -p /mnt/blobfuse
sudo blobfuse2 /mnt/blobfuse --config-file=fuse_connection.yaml
```
content of fuse_connection.yaml
```
# Logger configuration
logging:
  type: syslog
  level: log_warning
  file-path: "/home/azureuser/######/blobfuse2.log"

# Pipeline configuration
components:
  - libfuse
  - block_cache
  - file_cache
  - attr_cache
  - azstorage

# Azure storage configuration
azstorage:
  type: block       # Use "block" for blob storage; change to "adls" if using ADLS
  account-name: ########
  container: ########
  endpoint: https://#######.blob.core.windows.net/  # Adjust endpoint based on your storage account
  mode: msi        # Use "msi" for managed identity
  # No need for account-key or sas since you are using MSI

# Block cache related configuration (optional; adjust based on your needs)
block_cache:
  block-size-mb: 16
  mem-size-mb: 512
  path: /mnt/resource/blobfusetmp/block_cache  # Ensure this directory exists
  disk-size-mb: 10240  # Adjust as necessary
  disk-timeout-sec: 120
  prefetch: 11         # Set to at least 11
  parallelism: 4

# Disk cache related configuration (adjust path as needed)
file_cache:
  path: /mnt/resource/blobfusetmp/file_cache  # Ensure this directory exists
  timeout-sec: 120
  max-size-mb: 10240  # Adjust as necessary
```
