### ISSUE TITLE
Blobfuse not writing to HNS enabled Storage Account fast enough

### ISSUE THREAD

**Issue by biggles007** [Azure/azure-storage-fuse#1573]
Blobfuse version: 2.3.2
Operating System: RHEL 8.6

The config file is as per below

```yaml
allow-other: true

# Logger configuration
logging:
  type: syslog #|silent|base <type of logger to be used by the system. silent = no logger, base = file based logger. Default - syslog>
  level: log_warning # log_off|log_crit|log_err|log_warning|log_info|log_trace|log_debug <log level. Default - log_warning> <log_debug will also enable sdk-trace logs>

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
  - block_cache
  - attr_cache
  - azstorage

# Block cache related configuration
block_cache:
  mem-size-mb: 5120
  path: /blobstorage/cache/archive2 # <path to local disk cache where downloaded blocked will be stored>

# Azure storage configuration
azstorage:
  type: adls
  account-name: ${account_name}
  container: ${container}
  endpoint: https://${account_name}.blob.core.windows.net
  mode: msi
  appid: ${msi_client_id}
```

# Server build/app

The server runs a third party Digital Asset Management system that writes to a shared file location, this has been mounted via Blobfuse2. Assets/images are being archived from a live production system (that isn't cloud based) to the archive server in Azure.

# Issue

The cache seems to becoming full with the data being copied in. With blobfuse not seemingly copying data into the Storage Account/Data Lake Storage at a reasonable rate. The blobfuse2 process isn't using any CPU, I can see a process of `/usr/bin/du -sh /blobstorage/cache/archive2` that appears every now and then with high CPU usage, seemingly calculating the space used.

Is there a way of monitoring Blobfuse and the rate at which it is copying files into the Storage Account?
