### ISSUE TITLE
Unable to mount adls gen2 blob containers from a storage account via MSI with private endpoints

### ISSUE THREAD

**Issue by vergilcw** [Azure/azure-storage-fuse#1592]
* The blobfuse2 package is not able to mount the blob containers from a storage account using msi on the aml compute instance, except with storage account key authentication which is not feasible from a security perspective. Any Entra-based authentication methods and identities fail to mount with Error 400. (tested versions `2.2.1`, `2.3.0`, and `2.4.0`)
* Our current theory is that something with dns or routing is preventing the authentication traffic from reaching Azure's Entra servers (since the token-based authentication works but not any other method).
* Enabled sdk and debug logging
* Tested mounting from both public compute instance (vweatherfordadmin1)  and private network compute instance (hailmarynumero2) with alternately UMI and System credentials plus SSO enabled. Our testing focused mainly on the private compute instance because we expect the public compute instance to fail given the storage is private 
* tried (temporarily) allowing the public IP of the public compute to access the storage account
* We thoroughly permutated the "msi" authentication mode parameters from this link: https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml with the following parameters (tested one at a time, and also tested with none of these):
    * `appid`
    * `resid`
    * `objid`
    * `msi_client_id`
* used the UMI, MSI, and even tried SPN identity types, confirmed contributor access to the storage account and container
*	Tested with the `azcli` auth type, but `az login -i` failed to login with the MSI credentials from the compute instance. When attemping az login with auth code as a user, blobfuse was unable to find the user token to attempt the login.
*	tried temporarily allowing DNS queries to bypass internal dns. 
*	Most of the errors given were `400 Identity not found` with `Identity is not assigned to this resource` except when we tried `azcli`, in which case the error was something like `please run az login to setup account` even though we had logged in already with `az login`.

CLI commands / steps to reproduce from the terminal in Azure ML Services:

To reproduce, you need an Azure ML workspace with a compute instance (we used a private network compute instance) and a storage account with an ADLS Gen2 container on a private endpoint. Confirm you can access the storage account from the compute instance using the storage account key. Then, try to mount the storage account using blobfuse2 with MSI authentication. Code snippets are below:

From terminal in Azure ML Services compute instance:
```
#test connectivity
dnslookup <storage-account-name>.dfs.core.windows.net
#(successfully resolving)

#install blobfuse deps:
sudo wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install libfuse3-dev fuse3
mkdir ~/test

#testing the mount

sudo blobfuse2 mount ~/test/ --config-file=./config.yaml
cat /var/log/blobfuse2.log | tail -n 15

```

contents of `config.yaml`:
```
allow-other: true

logging:
  type: syslog
  #level: log_err 
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/alg/.blobfuse2cache/alg/
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  sdk-trace: true
  type: adls
  account-name: <account-name-removed>
  container: storage-bronze
  mode: msi
  appid: <appid-redacted>
  endpoint: https://<account-name-removed>.dfs.core.windows.net
```
