### ISSUE TITLE
Missing data into the file

### ISSUE THREAD

**Issue by leascherf** [Azure/azure-storage-fuse#1596]
**Which version of blobfuse was used?**
blobfuse2 version: 2.4.0

**Which OS distribution and version are you using?**
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

**config-file used:**
```

# Logger configuration
logging:
  type: base
  level: log_warning
  file-path: /var/log/blobwarning.log

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
 # - block_cache
 # - file_cache
#  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 300
  entry-expiration-sec: 300
  negative-entry-expiration-sec: 300
# Block cache related configuration
#block_cache:
#  block-size-mb: 8 #<size of each block to be cached in memory (in MB). Default - 16 MB> estaba en 32
#  mem-size-mb: 500 #<total amount of memory to be preallocated for block cache (in MB). Default - 80% of free memory>
#  path: /var/cache/block_cache #<path to local disk cache where downloaded blocked will be stored>
#  disk-size-mb:  500 #<maximum disk cache size allowed. Default - 80% of free disk space>
#  disk-timeout-sec: 3600
#  prefetch: 11 # <number of blocks to be prefetched in serial read case. Min - 11, Default - 2 times number of CPU cores>
#  parallelism: 3 #<number of parallel threads downloading the data and writing to disk cache. Default - 3 times number of CPU cores> 

#attr_cache:
#  timeout-sec: 300

# Disk cache related configuration
#file_cache:
  # Required
 # path: /var/cache/file_cache
  # Optional 
  #timeout-sec: 3600
  #max-size-mb: 5120
```

**What was the issue encountered?**

I'm using the BlobFuse package to mount my Azure Blob storage into a Docker container. I have a Linux VM where I installed and configured BlobFuse, successfully mounting the blob storage. I've also configured my container to use the mounted path (/mnt/blob/).

I have a Selenium Grid setup with a Firefox container to automate the file download process, which saves the downloaded files directly into the blob storage.

The issue I'm experiencing is that some of the downloaded files have corrupted data.
```

Example: into good file

column 1, column2, column3
datax   , datay,   datae
...
...
When Download the file with selenium and save into the blob

Datay , datee
data  , data, data
...
...

```
**Have you found a mitigation/solution?**

NO

**Please share logs if available**

Logs:
```

Fri Dec 20 10:20:31 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob 03e2e349-d30b-4860-af1b-1b4a3ac1ea4d/Activity_12-20-2024_10-20-31_am.csv does not exist
Fri Dec 20 10:20:31 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [libfuse_handler.go (702)]: Libfuse::libfuse_open : Flags (8401) not supported to open 03e2e349-d30b-4860-af1b-1b4a3ac1ea4d/LOyzkQSY.csv.part when write back cache is on. Ignoring unsupported flags.
Fri Dec 20 10:20:31 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob 03e2e349-d30b-4860-af1b-1b4a3ac1ea4d/Activity_12-20-2024_10-20-31_am.csv does not exist
Fri Dec 20 10:20:31 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob 03e2e349-d30b-4860-af1b-1b4a3ac1ea4d/LOyzkQSY.csv.part does not exist
Fri Dec 20 10:28:35 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob b17397bd-9ba5-4379-93da-4638a7f06408/XyBteFQB.csv does not exist
Fri Dec 20 10:28:35 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob b17397bd-9ba5-4379-93da-4638a7f06408/XyBteFQB.csv.part does not exist
Fri Dec 20 10:28:35 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [libfuse_handler.go (702)]: Libfuse::libfuse_open : Flags (8201) not supported to open b17397bd-9ba5-4379-93da-4638a7f06408/XyBteFQB.csv.part when write back cache is on. Ignoring unsupported flags.
Fri Dec 20 10:28:35 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob b17397bd-9ba5-4379-93da-4638a7f06408/Investments_12-20-2024_10-28-35_am.csv does not exist
Fri Dec 20 10:28:35 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob b17397bd-9ba5-4379-93da-4638a7f06408/Investments_12-20-2024_10-28-35_am.csv does not exist
Fri Dec 20 10:28:35 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [libfuse_handler.go (702)]: Libfuse::libfuse_open : Flags (8401) not supported to open b17397bd-9ba5-4379-93da-4638a7f06408/XyBteFQB.csv.part when write back cache is on. Ignoring unsupported flags.
Fri Dec 20 10:28:35 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_ERR [block_blob.go (768)]: BlockBlob::ReadBuffer : Failed to download blob b17397bd-9ba5-4379-93da-4638a7f06408/XyBteFQB.csv.part [offset value is out of range]
Fri Dec 20 10:28:36 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob b17397bd-9ba5-4379-93da-4638a7f06408/XyBteFQB.csv.part does not exist
Fri Dec 20 10:49:29 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob e73da198-4242-4343-a1d8-b6ce9c1d5010/ouVQRKWP.csv does not exist
Fri Dec 20 10:49:29 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob e73da198-4242-4343-a1d8-b6ce9c1d5010/ouVQRKWP.csv.part does not exist
Fri Dec 20 10:49:29 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [libfuse_handler.go (702)]: Libfuse::libfuse_open : Flags (8201) not supported to open e73da198-4242-4343-a1d8-b6ce9c1d5010/ouVQRKWP.csv.part when write back cache is on. Ignoring unsupported flags.
Fri Dec 20 10:49:29 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob e73da198-4242-4343-a1d8-b6ce9c1d5010/Investments_12-20-2024_10-49-29_am.csv does not exist
Fri Dec 20 10:49:29 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [libfuse_handler.go (702)]: Libfuse::libfuse_open : Flags (8401) not supported to open e73da198-4242-4343-a1d8-b6ce9c1d5010/ouVQRKWP.csv.part when write back cache is on. Ignoring unsupported flags.
Fri Dec 20 10:49:29 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob e73da198-4242-4343-a1d8-b6ce9c1d5010/Investments_12-20-2024_10-49-29_am.csv does not exist
Fri Dec 20 10:49:29 EST 2024 : blobfuse2[1751026] : [/mnt/blob-storage] LOG_WARNING [block_blob.go (505)]: BlockBlob::getAttrUsingList : blob e73da198-4242-4343-a1d8-b6ce9c1d5010/ouVQRKWP.csv.part does not exist
```
