### ISSUE TITLE
the file cache is emptied on unmount

### ISSUE THREAD

**Issue by kforner** [Azure/azure-storage-fuse#1610]
I mount a HNS blob storage using blobfuse2, using a local cache directory.
When I access a file in the mount, I can see that it is indeed copied in the cache directory.
But as soon as I unmount the fuse mount, the local cache directory gets deleted.
Same behavior if I use `blobfuse2 unmount all` or `fusermount -u xxx`.

In the logs, just after the mount command, I can see this:
```
LOG_TRACE [libfuse_handler.go (345)]: Libfuse::libfuse_destroy : destroy
LOG_TRACE [libfuse.go (176)]: Libfuse::Stop : Stopping component libfuse
LOG_TRACE [libfuse_handler.go (253)]: Libfuse::destroyFuse : Destroying FUSE
LOG_TRACE [file_cache.go (181)]: Stopping component : file_cache
LOG_TRACE [lru_policy.go (153)]: lruPolicy::ShutdownPolicy
LOG_TRACE [attr_cache.go (116)]: AttrCache::Stop : Stopping component attr_cache
LOG_TRACE [azstorage.go (184)]: AzStorage::Stop : Stopping component azstorage
```

My questions: 
 - is it expected ? 
 - how can I prevent that?

My use case is to have persistent file caches, so that if I restart blobfuse, it could pickup where it stopped, and avoid downloading again files in the persistent cache.

## config

```
nonempty: true
# nonempty: true|false <allow mounting on non-empty directory>

logging:
  type: base
  level: log_debug
  #  type: syslog|silent|base <type of logger to be used by the system. silent = no logger, base = file based logger. Default - syslog>
  # level: log_off|log_crit|log_err|log_warning|log_info|log_trace|log_debug <log level. Default - log_warning> <log_debug will also enable sdk-trace logs>
  # file-path: <path where log files shall be stored. Default - '$HOME/.blobfuse2/blobfuse2.log'>
  # max-file-size-mb: <maximum allowed size for each log file (in MB). Default - 512 MB>
  # file-count: <maximum number of files to be rotated to preserve old logs. Default - 10>

components:
 - libfuse
 - file_cache
 - attr_cache
 - azstorage
 
# Libfuse configuration
libfuse:
  # time kernel can cache inode attributes (in sec). Default - 120 sec
  attribute-expiration-sec: 3600
  # time the kernel can cache directory listing. Default - 120 sec
  entry-expiration-sec: 3600
  # time kernel can cache attributes of non existent paths (in sec). Default - 120 sec
  negative-entry-expiration-sec: 3600
  # default-permission: 0777|0666|0644|0444 <default permissions to be presented for block blobs>
  # fuse-trace: true|false <enable libfuse api trace logs for debugging>
  # extension: <physical path to extension library>
  # direct-io: true|false <enable to bypass the kernel cache>

  # 
 
## Disk cache related configuration
file_cache:
  # ======= required ===============
  # path to local disk cache
  path: .cache

  # ======= optional ===============
  # default cache eviction timeout (in sec). Default - 120 sec
  timeout-sec: 3600
  # maximum cache size allowed. Default - 80% of free disk space
  # max-size-mb: 80
  # true|false <allow non empty temp directory at startup>
  allow-non-empty-temp: true
  # true|false <cleanup the temp directory on startup, if its not empty>
  cleanup-on-start: false
  # sync-to-flush: true|false <sync call to a file will force upload of the contents to storage account>
  # number of seconds after which compare LMT of file in local cache and container and refresh file if container has the latest copy>. Default - 120 sec
  refresh-sec: 3600
  # ignore-sync: true|false <sync call will be ignored and locally cached file will not be deleted>
  # hard-limit: true|false <if set to true, file-cache will not allow read/writes to file which exceed the configured limits>
 
attr_cache:
  # <time attributes can be cached (in sec). Default - 120 se
  timeout-sec: 3600
  # no-symlinks: true|false <to improve performance disable symlink support. symlinks will be treated like regular files.> 


azstorage:
 type: adls
```

## info
blobfuse2 version 2.4.0 in a docker container running Ubuntu 22.04.5
