### ISSUE TITLE
File open error for storage mounted with subdirectory and block cache.

### ISSUE THREAD

**Issue by listcrawler** [Azure/azure-storage-fuse#1612]
When mounting a storage subdirectory with a block cache, opening of files may fail. Using a file cache or without a subdirectory shows no such problems.

```bash
$ sha256sum somefile.bin
LOG_TRACE [libfuse_handler.go (687)]: Libfuse::libfuse_open : somefile.bin
LOG_TRACE [block_cache.go (385)]: BlockCache::OpenFile : name=somefile.bin, flags=32768, mode=-rwxrwxrwx
LOG_TRACE [attr_cache.go (472)]: AttrCache::GetAttr : somefile.bin
LOG_DEBUG [attr_cache.go (482)]: AttrCache::GetAttr : somefile.bin served from cache
LOG_ERR [block_cache.go (389)]: BlockCache::OpenFile : Failed to get attr of somefile.bin [no such file or directory]
LOG_ERR [libfuse_handler.go (721)]: Libfuse::libfuse_open : Failed to open somefile.bin [no such file or directory]
sha256sum: somefile.bin: No such file or directory
```

Inside the directory, some files can be opened and others not, seemingly arbitrarily. The success and failures are consistent across remounts though. The storage has a flat namespace and block blobs.

From what I can discern, the failing code path is like this:
1. [attr_cache.go:GetAttr returns an ENOENT error](https://github.com/Azure/azure-storage-fuse/blob/32ba9ccff233795b83121f0bbab482b2a651ad14/component/attr_cache/attr_cache.go#L484).
2. [block_cache.go:OpenFile picks up the error and returns the same ENOENT error](https://github.com/Azure/azure-storage-fuse/blob/32ba9ccff233795b83121f0bbab482b2a651ad14/component/block_cache/block_cache.go#L390).
3. [libfuse_handler.go:libfuse_open picks up the error and fails](https://github.com/Azure/azure-storage-fuse/blob/32ba9ccff233795b83121f0bbab482b2a651ad14/component/libfuse/libfuse_handler.go#L723).

config.yaml:
```yaml
allow-other: true

logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - block_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
  fuse-trace: true

block_cache:
  path: /tmp/blobfuse/block_cache
  block-size-mb: 32
  mem-size-mb: 8192
  prefetch: 20
  parallelism: 32

file_cache:
  path: /tmp/blobfuse/file_cache

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
```

Invoking blobfuse2 with `--subdirectory=somefolder` then may exhibit this failure. Not passing the subdirectory option or using a file cache seems to work well.

This was all done in wsl2.
