### ISSUE TITLE
RAM lacking after upgrading blobfuse2 from blobfuse2-2.3.2 to blobfuse2-2.4.0

### ISSUE THREAD

**Issue by Werpak** [Azure/azure-storage-fuse#1617]
Hello,
I was using blobfuse2-2.3.2 but with upgrade to blobfuse2-2.4.0 I'm experiencing RAM leaking after upgrade.
OS: Red Hat Enterprise Linux 8.10

I'm using blobfuse2 to push data from VMSS nodes into blob storage - every node is writing data into blob constantly - files are divided/distinguished by date and hours (every passing hour is next new file).

After upgrading to newest version my memory looks like this:

![Image](https://github.com/user-attachments/assets/d7fb3abd-2cd3-4016-922d-63e375376589)
and eventually going to 0 with error:

![Image](https://github.com/user-attachments/assets/0fa82253-5eb9-4f24-8b45-61ab7d8925b0)
RAM on every machine is 8GM. I'm limiting memory usage for blobfuse2 up to 4GB leaving another 4GB for other apps and OS.

I was using stream config before upgrade for more than year without issues, but I learned that stream mode was changed in newest version to block-cache, so I changed config to this:
```

logging:
  type: syslog
  level: log_info

components:
  - libfuse
  - stream
#  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
  ignore-open-flags: true

#stream:
block_cache:
  block-size-mb: 32
  mem-size-mb: 4096
  prefetch: 64
  parallelism: 16
  file-caching: false


#attr_cache:
#  timeout-sec: 7200

azstorage:
  type: block
  account-name:
  account-key:
  endpoint:
  mode: key
  container:
```

Please help me understand if my config is correct and how to overcome this RAM issue.
