### ISSUE TITLE
Is the following setup valid (sftp blob to fuse on linux)

### ISSUE THREAD

**Issue by MalfuncEddie** [Azure/azure-storage-fuse#1624]
I've got an azure blob sftp server. Files are uploaded there and a linux machine mounts this via fusefs. Sometime we notice that there are empty files. 

The files are processed after the sftp sessions. So they are quite rapidly "processed" and it feels that the files on linux aren't yet there. 

Is this something I can fix on the fuse fs side without resorting to az copy? 

mount options config file

```

allow-other: true
nonempty: true

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - block_cache
  - attr_cache
  - azstorage

libfuse:
  default-permission: 0666
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /fusecache
  max-size-mb: 1024
  timeout-sec: 120

block_cache:
  block-size-mb: 32
  mem-size-mb: 4096
  prefetch: 80
  parallelism: 128

attr_cache:
  no-symlinks: true
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: censored
  container: censored
  mode: msi
  objid: censored


```

fuse-libs-2.9.7-16.0.1.el8.x86_64
fuse-common-3.3.0-16.0.1.el8.x86_64
fuse3-libs-3.3.0-16.0.1.el8.x86_64
blobfuse2-2.3.2-1.x86_64
fuse3-3.3.0-16.0.1.el8.x86_64

Oracle enterprise linux 8.8
