### ISSUE TITLE
Clarification - temporary network interruption

### ISSUE THREAD

**Issue by casimir-dus** [Azure/azure-storage-fuse#1632]
Hi all,

we will have a short network maintenance which will disconnect the server running blobfuse from the internet for approx 15 minutes.
What happens if a client tries to write a new file to the mounted folder in this time?
We use file caching.

Thanks in advance!

**Comment by syeleti-msft** [comment]
Hi @casimir-dus, It depends on the configuration file for your blobfuse mount.
If network interruption happens **after** opening the file then all the writes will be success, but the call to the "close" operation would fail.
If network interruption happens **before** opening the file, then the status of the open file depends on the timeout you set for the following parameters in your config file.
```
libfuse:
  attribute-expiration-sec: 300
  entry-expiration-sec: 300
  negative-entry-expiration-sec: 300

attr_cache:
  timeout-sec: 300
```
If the timeout has not expired then the open/create call to the file may still get success and subsequent writes would get success but eventually "close" operation would fail on the file.
To avoid such behaviors, avoid setting the timeout values to large and always check the status of the close()/fsync() operation in your user application.

Thanks!
