### ISSUE TITLE
blobfuse2 health monitor logs are empty

### ISSUE THREAD

**Issue by HarshadDGhorpade-eaton** [Azure/azure-storage-fuse#1656]
I am facing weird issue with health monitor logs, below is my blobfuse2 config yml
```
allow-other: true
logging:
  type: syslog
  level: log_debug
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage
libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
file_cache:
  path: /mnt/cache-container-temp
  timeout-sec: 120
attr_cache:
  timeout-sec: 7200
azstorage:
  type: block
  account-name: accnt
  sas: ***
  endpoint: https://accnt.blob.core.windows.net/
  mode: sas
  container: cache-container
health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  output-path: /__w/workspace/a/blobfuse2
```

Command:
```
blobfuse2 mount $cache_folder_path --config-file=${{ env.WORKSPACE }}/az_storage_cache_config.yml --log-level LOG_DEBUG --log-file-path ${{ env.BLOBFUSE2_ARTIFACTS_PATH }}/blobfuse2.log

```
I am trying to ls into the directory `output-path` right after blobfuse2 mount command but I am not able to find health monitor log file, but when I archive the artifacts from `output-path` directory, I do see an empty log file with name `monitor_pid.json` along with blobfuse2 log.

blobfuse2 log has below entry when I try to search `health` :
```
LOG_DEBUG [health-monitor.go (102)]: health-monitor : Options = [--pid=820 --stats-poll-interval-sec=10 --process-monitor-interval-sec=30 --output-path=/__w/workspace/a/blobfuse2 --cache-path=/mnt/cache-container-temp --max-size-mb=0]
LOG_DEBUG [health-monitor.go (103)]: health-monitor : Starting health-monitor for blobfuse2 pid = 820
```

I am not sure if there should be more entries where it mentons it finished health monitor, but I dont see it in logs

we use blobfuse2 v2.4.0

![Image](https://github.com/user-attachments/assets/dd009468-54db-453c-8458-f7794904dc1f)
