### ISSUE TITLE
Changes made to files in container is not reflecting in VM

### ISSUE THREAD

**Issue by VijayaraghavanPS** [Azure/azure-storage-fuse#1679]
blobefuse2 version: 2.4.0

OS distribution: Ubuntu 22.04

Issue encountered:
I have a VM where I'm using Blobfuse2 to mount a container from an Azure Storage account. After mounting, I'm able to view, edit, and create files from the VM, and any changes I make are successfully reflected in the blob container.

In my scenario, other applications also update files directly in the same container via the storage account. The issue is that changes made to existing files by these external applications are not reflected in the Blobfuse mount on the VM. But, any new files created by these applications do show up in the mount, but modifications to existing files do not.

I’ve tried setting the cache expiration time to `0`, but it didn’t resolve the problem. 

Config.yaml:

```
logging:
  level: log_debug
  file-path: /var/log/blobfuse2-ws.log
  type: base
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage
libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 120
file_cache:
  path: /mnt/blobfuse-ws-cache
  timeout-sec: 120
  tmp-path: /mnt/blobfuse-ws-tmp
attr_cache:
  timeout-sec: 120
azstorage:
  account-name: xxx
  container: xxx
  type: adls
  mode: msi
```

**Comment by VijayaraghavanPS** [comment]
Thank you for the quick response. Should I use -o direct_io as a cli parameter or should I use it in the config file like direct_io = true

**Comment by vibhansa-msft** [comment]
Both have the same effect, easier is to just add "-o direct_io" in your mount command (cli parameter)

**Comment by VijayaraghavanPS** [comment]
Thanks. The sync is working fine after adding "-o direct_io".
I would also like to understand how this will affect caching. 
I have set my config. yaml as
```
libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 120
file_cache:
  path: /mnt/blobfuse-ws-container-cache
  timeout-sec: 120
  tmp-path: /mnt/blobfuse-ws-container-tmp
attr_cache:
  timeout-sec: 120
```

I edited a file in container. Then opened it immediately in the VM and I can see the changes. Is  "-o direct_io" it disable all cache by overwriting the config values or is it in effect only when a file is opened.
