### ISSUE TITLE
rmdir succeeds on non-empty directories when using blobfuse2 v2.4.0+

### ISSUE THREAD

**Issue by topcon-xchai** [Azure/azure-storage-fuse#1687]
### Environment:

**OS:** Debian 11
**blobfuse2 version:** 2.4.0+ (reproducible on latest release)
**Works correctly on:** 2.3.2 and below
**Filesystem:** Mounted blob container via blobfuse2
**Mount configuration:** `blobfuse2 mount all /data --config-file=fuse2_connection.yml`
**File Cache mount configuration:** via _rc.local:_ `mount -t tmpfs -o size=2g tmpfs /tmp_blobfuse`
**Azure Storage:** StorageV2 (general purpose v2), HNS Disabled

### Bug Description:

It appears that since blobfuse2 version 2.4.0, it is possible to delete a blobfuse2 directory _(rmdir)_ even if it is not truly empty, as long as the files have been cleared from the blobfuse cache.

This is a critical issue for us. In our application logic, we delete files and then recursively attempt to delete parent directories only if they are empty,:
```
delete file
try to delete parent directory (Filesystem will block if not empty)
if success
try to delete parent's parent directory (Filesystem will block if not empty)

combined with a blobfuse2 issue is the problem.
``` 

Normally, the filesystem correctly blocks deletion of non-empty directories. However, due to this blobfuse2 behavior since 2.4.0, _rmdir_ succeeds even when the directory still contains files, resulting file deletion ends up deleting the entire directory (and all files in it) instead of just the target file.

Downgrading to blobfuse2 v2.3.2 or earlier eliminates the issue, confirming it was introduced since v2.4.0 (Since Dec. 2024).

**Expected Behavior:**
rmdir should fail if the target directory still contains blobs, regardless of blobfuse's local cache state.

**Actual Behavior:**
After file deletion and cache expiration, rmdir succeeds even though the corresponding blobs still exist in the mounted container.

**Reproduction Script:**
Below is a minimal Bash script we use to reproduce the issue:
```
#!/bin/bash

numFiles=4
mountPoint="/data/files"
cacheDir="/tmp_blobfuse/files"

newDir=`head -c8 /dev/urandom | xxd -ps`

blobfuse2 version
echo


echo "Creating new directory $mountPoint/$newDir"
mkdir -p "$mountPoint/$newDir"

echo "Creating $numFiles 128-byte files in directory"
for i in $( seq 1 $numFiles ); do
	head -c128 /dev/urandom > "$mountPoint/$newDir/file$i"
done

echo
date
echo "Number of files in directory: `ls -1 "$mountPoint/$newDir/" | wc -l`"
echo "Number of files in cache:     `ls -1 "$cacheDir/$newDir/" | wc -l`"

rmdir "$mountPoint/$newDir"
if [ $? -eq 0 ]; then
	echo "rmdir SUCCESS - This is unexpected!"
else
	echo "rmdir FAILED - OK"
fi

echo
echo "Wait for 4 minutes..."
sleep 60
echo "3 more minutes..."
sleep 60
echo "2 more minutes..."
sleep 60
echo "Just one more minute..."
sleep 60

echo
date
echo "Number of files in directory: `ls -1 "$mountPoint/$newDir/" | wc -l`"
echo "Number of files in cache:     `ls -1 "$cacheDir/$newDir/" | wc -l`"

rmdir "$mountPoint/$newDir"
if [ $? -eq 0 ]; then
	echo "rmdir SUCCESS - Regardless of directory not empty!"
else
	echo "rmdir FAILED - OK"
fi
``` 

**YAML Configuration:**
```
allow-other: true
nonempty: true
logging:
    type: syslog
libfuse:
    attribute-expiration-sec: 240
    entry-expiration-sec: 240
    negative-entry-expiration-sec: 120
file_cache:
    path: /tmp_blobfuse
    timeout-sec: 120
attr_cache:
    timeout-sec: 1800
azstorage:
    account-name: xxxxxxxxxxxxxxxx
    account-key: xxxxxxxxxxxxxxxx
    endpoint: xxxxxxxxxxxxxxxx
    update-md5: false
    validate-md5: false
    virtual-directory: true
    max-results-for-list: 0
    disable-compression: false
    telemetry: ""
    honour-acl: false
    cpk-enabled: false
    cpk-encryption-key: ""
    cpk-encryption-key-sha256: ""
mountall:
    container-allowlist:
    - storage
    - backups
    - files
components:
    - libfuse
    - file_cache
    - attr_cache
    - azstorage
```
