### ISSUE TITLE
Directory listing is very slow

### ISSUE THREAD

**Issue by AlexeyShaferov** [Azure/azure-storage-fuse#784]
Hello!

### Which version of the blobfuse was used?
blobfuse 1.4.2

### Which OS (please include version) are you using?
Ubuntu 21.10

### What problem was encountered?
Obtaining a list of a contents of a directory with a large number of entries takes a lot of time. It is much (much!) slower than to get a list of a similar directory mounted with SMB. I have two storage accounts, each has one container (or a File Share) with a root directory that contains 31268 entries inside. 

#### The first storage account (Datalake 2, mounted with `blobfuse`):
Performance: Premium
Replication: Locally-redundant storage (LRS)
Account kind: BlockBlobStorage
Provisioning state: Succeeded

Hierarchical namespace: Enabled
Blob public access: Enabled
Blob soft delete: Enabled (7 days)
Container soft delete: Enabled (7 days)
Versioning: Disabled
Change feed: Disabled
NFS v3: Disabled
SFTP (preview): Disabled

#### The second storage account (File Share, mounted with simple `mount` command)
Performance: Premium
Replication: Locally-redundant storage (LRS)
Account kind: FileStorage
Provisioning state: Succeeded

Large file share: Enabled
Active Directory: Not configured
Soft delete: Enabled (7 days)

#### A simple speed test
```
time ls -l /mnt/azure/
```

Result for the first (`blobfuse` mounted) account:
```
real	33m17,541s
user	0m0,307s
sys	0m1,120s
```

Result for the second (`SMB` mounted) account:
```
real	0m22,157s
user	0m0,112s
sys	0m0,448s
```
As you can see, the difference is huge. Is it possible to speedup the `blobfuse`?

### If relevant, please share your mount command.
`blobfuse /mnt/azure/ --tmp-path=/tmp/blobcache/ --config-file=~/Desktop/blob.conf`

P.S: Yes, I know that a directory with 31268 entries is a bad idea, but this project is not started by me, and there a lot of code that works with these files. It is impossible to change directory structures.

**Comment by tasherif-msft** [comment]
Hi @AlexeyShaferov, we have actually been working on different performance improvements + features on a new BlobFuse package that is currently in preview (BlobFuseV2)

Please do give it a try and see if it improves your perf scenario:
 https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview.1

Here's how you can set up the mount:
 https://github.com/Azure/azure-storage-fuse/tree/main
Any feedback would be appreciated as we prepare for the second preview :)

**Comment by vibhansa-msft** [comment]
When you list a directory mounted using blobfuse (any fuse2 compliant FS for that matter), there is one call to get the list of items in that directory. From Azure backend we can get only 5K items at max in one iteration so depending on the total number of files there will be multiple network trips to get the entire list. Once blobfuse returns back this list to kernel, kernel fires a storm of getAttr on each of those items to retrieve metadata of each item. If certain attributes are not configured properly then each such getAttr will also result into a list/getattr call over network to backend. You need to provide attribute-timeout, negative-timeout and turn on attribute-cache to improve performance here. This is no limitation from blobfuse end, rather its from azure server and how fuse-based system works.

**Comment by AlexeyShaferov** [comment]
> Please do give it a try and see if it improves your perf scenario:
Thank you for your answer!

Yes, the new version works much faster:
```
time ls -l /mnt/tmp/
.....................
real	0m18,357s
user	0m0,135s
sys	0m0,135s
```
But some of my content is missing. Here is a screenshot from MC:
![image](https://user-images.githubusercontent.com/87761000/169062956-48e21a0b-1a02-41c0-be09-35b95506fb9c.png)
And here is how it should look like:
![image](https://user-images.githubusercontent.com/87761000/169063187-c617aa74-5d70-4533-bdeb-4e519c5af2b1.png)
As you can see, a lot of directories are inaccessible. 

My config file is:
```
#allow-other: true
read-only: true
foreground: true

logging:
  type: base
  level: log_warning
  file-path: ./blobfuse.log

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /tmp/blobfuse-cache
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: savimanadatacollection02
  endpoint: 'https://savimanadatacollection02.blob.core.windows.net'
  mode: key
  account-key: 'keykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeyke=='
  container: 'anootation-stations-container'
```

So I can assume that a lost directories is the reason of good speed. :-)

**Comment by AlexeyShaferov** [comment]
Sorry, But I am not sure that empty files you are talking about. Anyway, this is a filtered list of directories that exists in the container, but it is not visible in the Midnight Commander at the `/mnt/tmp` mount point:
![image](https://user-images.githubusercontent.com/87761000/169246753-b137dfc1-7e44-4864-b90b-413e04e89789.png)
As I can see, there are dirs only. 

And here is a filtered list of directories that also accessible through BlobFuse, and visible at the `/mnt/tmp` mount point
![image](https://user-images.githubusercontent.com/87761000/169247434-c1bff762-face-49e9-a904-cee646883eb6.png)

Do you mean that I should check for these files inside of these dirs?

**Comment by vibhansa-msft** [comment]
No what I meant is when you filter a directory name, you shall see one directory and one file with exactly the same name. Which is not the case as per your filters. Can you confirm this is gen2 (HNS enabled) account or not? If so we need to change a few things in config.

**Comment by AlexeyShaferov** [comment]
Yes. Hierarchical namespace is enabled. 
![image](https://user-images.githubusercontent.com/87761000/169264853-22da7dfc-ecdd-4d5d-81e3-99a5c1da84f4.png)

**Comment by vibhansa-msft** [comment]
In that case you need to correct your config to below : 
azstorage:
  type: **adls**
  account-name: savimanadatacollection02
  endpoint: 'https://savimanadatacollection02.**dfs**.core.windows.net'

**Comment by AlexeyShaferov** [comment]
> In that case you need to correct your config to below :

Ok. My new config is:
```
#allow-other: true
read-only: true
foreground: true

logging:
  type: base
  level: log_warning
  file-path: ./blobfuse.log

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /tmp/blobfuse-cache
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: savimanadatacollection02
  endpoint: 'https://savimanadatacollection02.dfs.core.windows.net'
  mode: key
  account-key: 'keykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeyke=='
  container: 'anootation-stations-container'
```

But a listing result is the same:
![image](https://user-images.githubusercontent.com/87761000/169268969-75f32487-677f-4d97-a35b-592348549a8d.png)
