### ISSUE TITLE
blobfuse2 + azurite storage emulator

### ISSUE THREAD

**Issue by bluebrown** [Azure/azure-storage-fuse#869]
Hi, I am trying to make blobfuse2 with azurite work.

I build blobfus2 from the main branch

```Dockerfile
FROM golang
RUN git clone --branch main https://github.com/Azure/azure-storage-fuse.git /tmp/azure-storage-fuse
WORKDIR /tmp/azure-storage-fuse
RUN apt update -y
RUN apt-get -y install libfuse3-dev
RUN go build -o /tmp/blobfuse2

FROM ubuntu
COPY --from=0 /tmp/blobfuse2 /usr/bin/
RUN apt update -y
RUN apt-get -y install libfuse3-dev
```

and launch the below compose stack.

```yaml
name: blobfuse2-test

services:
  storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite:3.18.0
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 80
    ports:
      - 10000:80
    networks:
      default:
        aliases:
          - devstoreaccount1.blob.core.dev.local
    volumes:
      - storage:/data

  fuser:
    build: ./
    command: sleep inf
    cap_add: [ SYS_ADMIN ]
    devices: [ /dev/fuse ]
    volumes:
      - ./config.yaml:/config.yaml

volumes:
  storage:
```

After creating the a container with name assets via storage explorer. I exec into the fuser container and try to execute blobfuse2 with the following config file.

```yaml
foreground: true

components:
  - libfuse
  - stream
  - file_cache
  - attr_cache
  - azstorage
  - loopbackfs

logging:
  type: syslog
  level: log_debug
  track-time: true

file_cache:
  path: /tmp

azstorage:
  type: block
  use-http: true
  account-name: devstoreaccount1
  endpoint: blob.core.dev.local
  account-key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
  mode: key
  container: assets
  sdk-trace: true
```

I tried different combinations but I always get authentication errors:

```
root@6b917ed7feb6:/# mkdir mnt/test
root@6b917ed7feb6:/# blobfuse2 mount /mnt/test/ --config-file config.yaml 
failed to mount : failed to authenticate credentials for azstorage
```

**Comment by bluebrown** [comment]
I found out that the endpoint needs to contain the full hostname `devstoreaccount1.blob.core.dev.local`. Additionally, the `loopbackfs` path is missing in this config.  After fixing those 2, it appears to work as expected.

**Comment by gapra-msft** [comment]
Hi @bluebrown, the loopbackfs component is not necessary and is moreso for testing other components in blobfuse2. You should be able to remove it and it should work as expected.

Yes, the endpoint is required in blobfuse2, so the full hostname is necessary.

**Comment by bluebrown** [comment]
Hi @gapra-msft, thanks you for the quick response. 

Yes, I was able to remove loopbacks from the components and didn't need the corresponding configuration afterwards.

After testing, I can also confirm that the SYS_ADMIN cap and /dev/fuse device are required when using this in a docker container.

A side question: is this concurrency safe? Say I mount the storage with blobfuse2 into a docker volume and then mount this volume to multiple other containers?
I know the blob storage volume in Kubernetes that is currently in preview is read-write-many, and I believe it's based on blob fuse. I want to simulate our kubernetes setup this way.

**Comment by gapra-msft** [comment]
@bluebrown The limitations specified [here ](https://github.com/Azure/azure-storage-fuse#if-your-workload-is-read-only) apply to both blobfuse v1 (blobfuse) as well as blobfuse v2 (blobfuse2).

If you are mounting a different container, it is fine. But mounting the same container can result in unexpected behavior if your workload is not read only.

**Comment by bluebrown** [comment]
Hi, thanks for the info. Now I am wondering how the volume in AKS can be readWriteMany as shown in this example https://docs.microsoft.com/en-us/azure/aks/azure-blob-csi?tabs=Blobfuse#using-a-statefulset.

**Comment by gapra-msft** [comment]
I think this means ReadWriteMany in the context of that single mount, but I will double check that and get back to you.

**Comment by bluebrown** [comment]
Perhaps we think the same thing and there is a misunderstanding. Because moun can be the mount blobfuse is doing or the one the container is doing. 

I mean doing something like this

```yaml
services:
  # emulate the storage account
  storage-emulator:
    build: ./storage-emulator/
    environment:
      ENSURE_CONTAINERS: mydata
    ports:
      - 10000:80
    volumes:
      - storage-account-data:/data

  # create a single instance of blobfuse that mounts the blobfs
  # into a docker volume
  blobfuse2:
    build: ./blobfuse2/
    environment:
      AZURE_STORAGE_ACCOUNT: devstoreaccount1
      AZURE_STORAGE_ACCESS_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      AZURE_STORAGE_BLOB_ENDPOINT: storage-emulator/devstoreaccount1
      AZURE_STORAGE_ACCOUNT_CONTAINER: mydata
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    depends_on:
      storage-emulator:
        condition: service_healthy
    volumes:
      - container-public:/mnt/container

  # mount the same volume as the blobfuse2 container
  # to multiple containers
  app:
    image: bluebrown/echoserver
    volumes:
      - container-public:/data
    deploy:
      replicas: 3

volumes:
  storage-account-data:
  container-public:
```
