### ISSUE TITLE
blobfusev2 - mount issue: config error in file_cache error [tmp-path not set]

### ISSUE THREAD

**Issue by bnapora** [Azure/azure-storage-fuse#905]
### Which version of the blobfuse was used?
blobfuse2 version 2.0.0-preview.3

### Which OS (please include version) are you using?
bnapora$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

This compute is a brand new Compute Instance

### What problem was encountered?
Used blobfuse2 config converter to create new blobfuse2 config yaml.  When attempting to mount I get the following error:
`failed to mount : config error in file_cache error [tmp-path not set]`

I'm hoping someone can take a look at my config below and see if find an issue

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
This is another issue, as I can't find where blobfuse2 is logging.  When run v1 log search I get nothing
`sudo grep blobfuse /var/log/syslog`

#### Setup mount folders
```
sudo mkdir /datamnts/azmldata01/cat-blobs01-v2 -p
sudo chown 777 /datamnts/azmldata01/cat-blobs01-v2
sudo mkdir /datamnts/blobfuse2-cache -p
sudo chown 777 /datamnts/blobfuse2-cache
sudo mkdir /etc/blobfuse2
sudo chown 777 /etc/blobfuse2
```

#### Blobfuse2 Config file
```
sudo touch /etc/blobfuse2/azmldata01_cat-blobs01-v2.yml
sudo chmod 777 /etc/blobfuse2/azmldata01_cat-blobs01-v2.yml

sudo bash -c 'cat << EOF > /etc/blobfuse2/azmldata01_cat-blobs01-v2.yml
allow-other: true
logging:
    type: syslog
    level: LOG_INFO
libfuse:
    attribute-expiration-sec: 240
    entry-expiration-sec: 240
    negative-entry-expiration-sec: 120
    disablewritebackcache: false
    ignoreopenflag: false
file_cache:
    path: /datamnts/blobfuse2-cache
    v1timeout: 0
    emptydircheck: false
azstorage:
    account-name: azmldata01
    account-key:************************************************************************************* [Hidden, but works with v1]
    endpoint: https://azmldata01.blob.core.windows.net
    container: cat-blobs01
    update-md5: false
    validate-md5: false
    useadls: false
    usehttps: false
    setcontenttype: false
    cacertfile: ""
components:
    - libfuse
    - file_cache
    - azstorage
EOF'
```

#### Blobfuse Mount Command
blobfuse2 mount /datamnts/azmldata01/cat-blobs01-v2 --config-file=/etc/blobfuse2/azmldata01_cat-blobs01-v2.yml
