### ISSUE TITLE
blobfuse v2 Logging Issues

### ISSUE THREAD

**Issue by bnapora** [Azure/azure-storage-fuse#906]
### Which version of the blobfuse was used?
blobfuse2 version 2.0.0-preview.3

### Which OS (please include version) are you using?
bnapora$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 20.04.4 LTS
Release: 20.04
Codename: focal

### What problem was encountered?
Can't find log file entries.  Attempting to troubleshoot blobfuse2 connection but can't seem to find log files.  
After running mount command:
`blobfuse2 mount /datamnts/azmldata01/cat-blobs01-v2 --config-file=/etc/blobfuse2/azmldata01_cat-blobs01-v2.yml`
Attempted to review syslog entires:
`sudo grep blobfuse /var/log/syslog`
But no entries appear there.

I've looked through v2 docs and don't see an alternate location for logging.
Below is config entries:
```
allow-other: true
logging:
    type: syslog
    level: LOG_INFO
libfuse:
    attribute-expiration-sec: 240
    entry-expiration-sec: 240
    negative-entry-expiration-sec: 120
    disablewritebackcache: false
    ignoreopenflag: false
file_cache:
    path: /datamnts/blobfuse2-cache
    v1timeout: 0
    emptydircheck: false
azstorage:
    account-name: azmldata01
    account-key:********************************************************
    endpoint: https://azmldata01.blob.core.windows.net
    container: cat-blobs01
    update-md5: false
    validate-md5: false
    useadls: false
    usehttps: false
    setcontenttype: false
    cacertfile: ""
components:
    - libfuse
    - file_cache
    - azstorage
```

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
None - this is problem

### If relevant, please share your mount command.
`blobfuse2 mount /datamnts/azmldata01/cat-blobs01-v2 --config-file=/etc/blobfuse2/azmldata01_cat-blobs01-v2.yml`
