### ISSUE TITLE
ignore-open-flags not working in preview

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/azure-storage-fuse#915]
### Which version of the blobfuse was used?
blobfuse2 version 2.0.0-preview.3

### Which OS (please include version) are you using?
CentOS Linux release 7.9.2009 (Core)

### What problem was encountered?
We are testing the usage of blobfuse2 for doing Oracle RMAN backups to Blob Storage.

```RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03002: failure of backup plus archivelog command at 09/26/2022 11:42:39
ORA-19504: failed to create file "/rmanfusebackup/step/archivelog/2022-09-26_1142_STEP_59010_1_k218mahd_20220926.arc"
ORA-27044: unable to write the header block of file
Linux-x86_64 Error: 103: Software caused connection abort
```

We had the problem previous using Blobfuse 1.4.4 and found that we had to set the '--ignore-open-flags=true' on command line or 'ignore-open-flags: true' in the config file.
I simply can't make it work now with preview.3

When trying to access the mountpoint after getting this error, I have been disconnected:
```rmanfusebackup]$ ls -l /rmanfusebackup
ls: cannot access /rmanfusebackup: Transport endpoint is not connected
```
### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
I did see this in the blobfuse2.log file:

Mon Sep 26 10:55:35 UTC 2022 : blobfuse2[15366] : LOG_ERR [libfuse_handler.go (628)]: Libfuse::libfuse_open : Flag (8201) not supported to open step/0/2022-09-26_1005/resume-backup-2022-09-26_1005-incr0-4233811267 when write back cache is on. Pass --disable-writeback-cache or --ignore-open-flag via CLI

So I thought I had mis-spelled it or something (--ignore-open-flag vs. --ignore-open-flags), but nothing works.

### If relevant, please share your mount command.

```
rmanfusebackup]$ cat /etc/blobfuse/blobfuseconfig.yaml
# Refer ./setup/baseConfig.yaml for full set of config parameters

#allow-other: false

logging:
  type: base
  level: log_debug
  max-file-size-mb: 32
  file-count: 10
  track-time: true

components:
  - libfuse
  - file_cache
  - azstorage

libfuse:
  default-permission: 0644
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
  # To support Oracle RMAN
  ignore-open-flag: true

file_cache:
  path: /mnt/blobfusetmp
  timeout-sec: 20
  max-size-mb: 30720
  allow-non-empty-temp: true
  cleanup-on-start: true

azstorage:
  type: block
  account-name: fusebackup
  account-key: <key>
  endpoint: https://<name>.blob.core.windows.net
  mode: key
  container: <container-name>
```

Mounting using:
blobfuse2 mount /rmanfusebackup --config-file=/etc/blobfuse/blobfuseconfig.yaml
