### ISSUE TITLE
Examples to use with SAS URL with blobfuse2

### ISSUE THREAD

**Issue by dashesy** [Azure/azure-storage-fuse#935]
### Which version of the blobfuse was used? 
2.0.0-preview.2

### Which OS (please include version) are you using? 
Ubuntu 18

### What problem was encountered?
1. The mount command example does not mention there needs to be a mountpoint:
> blobfuse2 mount --config-file=

2. The example config does not mention sas-token or how to use SAS URL in config.
Initial try I get this error that am not sure how to fix

```text
failed to mount : config error in azstorage [account endpoint not provided]
```

3. I had already account-name in the config, but the default "account-name.blob.core.windows.net" was not used to construct the endpoint.

4. Added "endpoint: https://account-name.blob.core.windows.net" to config (which was not mentioned in the documentation) and got authentication error

Copied the sas token to "sas" in config. It starts with "?sv=". No luck.

```text
failed to mount : failed to authenticate credentials for azstorage
```

### Have you found a mitigation/solution?

Yes. 

For one thing I had to quote the SAS token using quotations "?sv=..." in the yaml file. Now I did not see authentication error, but still did not see the files mounted.

Looking at the log I saw this error:

```text
LOG_ERR [libfuse2_handler.go (175)]: Libfuse::initFuse : failed to mount fuse
```

Finally fixed the above by removing "read-only" and "allow-other" from config. Not sure which one was causing the issue (I think read-only).

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?

```text
LOG_ERR [libfuse2_handler.go (175)]: Libfuse::initFuse : failed to mount fuse
```

**Comment by tasherif-msft** [comment]
Hi @dashesy, please refer to https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml
For the azstorage component you need to provide the following for your credentials if using a sas token:
```
azstorage:
  type: block
  account-name: <name of the storage account>
  endpoint: <storage account endpoint (example - https://account-name.blob.core.windows.net)>
  sas: <storage account sas>
  mode: sas
  container: <name of the storage container to be mounted>
```

I did notice that our docs do not make it clear what's required. I will put out a PR to fix that. Thanks for the feedback :) 
Please do let me know if this works for ya
