### ISSUE TITLE
no logs from blobfuse2 health monitor

### ISSUE THREAD

**Issue by Mmdixon** [Azure/azure-storage-fuse#941]
### Which version of the blobfuse was used?
`blobfuse2 version 2.0.0-preview.3`

### Which OS (please include version) are you using?
Ubuntu 20.04

### What problem was encountered?
Don't see any health monitor logs anywhere. Check the current directory, checked `/blob/monitor/`, directories are owned by user, did some `ls` and `cat` commands on the blob mount and waited 30s.

### Have you found a mitigation/solution?
No

### By default, blobfuse logs errors to syslog. If this is relevant, is there anything in the syslog that might be helpful?
No mention of a health monitor anywhere in `/var/log/blobfuse2.log` at level `log_debug`

### If relevant, please share your mount command.
```
health_monitor:
  enable-monitoring: true
  stats-poll-interval-sec: 10 # <Blobfuse2 stats polling interval (in sec). Default - 10 sec>
  process-monitor-interval-sec: 30 # <CPU, memory and network usage polling interval (in sec). Default - 30 sec>
  output-path: /blob/monitor/
```
