### ISSUE TITLE
Azure Stack Hub blob mount failed

### ISSUE THREAD

**Issue by eti001** [Azure/azure-storage-fuse#945]
### Which version of the blobfuse was used?
Note: If you are using blobfuse 1.X.X, we would like to encourage you to try out the next generation of blobfuse, [blobfuse2](https://github.com/Azure/azure-storage-fuse/tree/main) which is currently in preview. The latest preview binaries can be found [here](https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview2) and more information on how to convert config options can be found [here](https://github.com/Azure/azure-storage-fuse/blob/main/MIGRATION.md#blobfuse-v2-guide-for-mapping-options-from-v1xx-to-v2xx). We will continue to respond to bug reports for blobfuse 1.X.X, however, no more feature requests will be considered.

blobfuse2 2.0.0-preview.3

### Which OS (please include version) are you using?

CentOS Stream release 8

### What problem was encountered?

When mounting Azure Stack Hub blob container, I receive:
`
Failed to validate storage account (failed to authenticate credentials for azstorage)`

And in the log:

```
===== RESPONSE ERROR (ServiceCode=) =====
Description=The value for one of the HTTP headers is not in the correct format.
RequestId:b2376dd2-60f4-0161-73ad-fb71396acb9d
Time:2022-10-18T12:21:30.4633357Z, Details:
   Code: InvalidHeaderValue
   HeaderName: x-ms-version
   HeaderValue: 2020-08-04
   GET https://<container.region.domain.name>/<blobstore>?comp=list&delimiter=%2F&maxresults=2&restype=container&timeout=3601
   Authorization: REDACTED
   User-Agent: [Azure-Storage-Fuse/2.0.0-preview.3 (CentOS Stream 8) Azure-Storage/0.14 (go1.16.2; linux)]
   X-Ms-Client-Request-Id: [0d56e3ba-138a-4476-7344-4baa6a77bc81]
   X-Ms-Date: [Tue, 18 Oct 2022 12:21:30 GMT]
   X-Ms-Version: [2020-08-04]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 The value for one of the HTTP headers is not in the correct format.
   Content-Length: [328]
   Content-Type: [application/xml]
   Date: [Tue, 18 Oct 2022 12:21:30 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [b2376dd2-60f4-0161-73ad-fb71396acb9d]


)
```

### Have you found a mitigation/solution?

Not yet, I suppose the problem is that the blobfuse2 (and libfuse) using a newer API version for storage, than the supported one by Azure Stack Hub, which is 2019-08-08 currently.

Thanks,
Tibor

**Comment by vibhansa-msft** [comment]
As you can see in above logs that you have posted, blobfuse2 is using 'X-Ms-Version: [2020-08-04]'.
How does this fail the authentication though? what mode of authentication you are using?

**Comment by eti001** [comment]
Oh, sorry, I totally forget:
It is a simple key based auth:

azstorage:
```
# Required
  type: block
  account-name: etdemolinux
  container: democentos
  endpoint: https://etdemolinux.blob.<region.domain.name>
  mode: key
  account-key: <current key>

```

**Comment by vibhansa-msft** [comment]
If you are using account-key as auth mode then there is no reason for it to fail due to x-ms-version I believe. There shall be something else going wrong with the system. Can you share you mount command and complete config file.

**Comment by vibhansa-msft** [comment]
Request ids provided in above logs are not traceable for me. Can you generate some fresh requests that are failing and share the similar sdk trace log. I can search these logs on the backend based on that.

**Comment by vibhansa-msft** [comment]
" endpoint: https://etdemolinux.blob.<region.domain.name>" : What do you mean by this statement. Is it "<account>.blob.core.windows.net" or something else?

**Comment by eti001** [comment]
Hi, endpoint is different than Azure one, it's unique in every AzureStack Hub installation, so It's not the blob.core.windows.net, but <accountname>.blob.<region>.<unique domain name>

So, the mount command:
`blobfuse2 mount /mnt/blob/ --config-file /root/ashBaseConfig.yaml/blobfuse2.log`

And the config file:
[ashBaseConfig.zip](https://github.com/Azure/azure-storage-fuse/files/9819916/ashBaseConfig.zip)

The key and URL is replaced.
Log attached too, its debug level log. Domain name is replaced.
[bl2log.log](https://github.com/Azure/azure-storage-fuse/files/9820018/bl2log.log)

**Comment by vibhansa-msft** [comment]
Can you replace your config with the below one and try again
```
# Logger configuration
logging:
  type: syslog
  level: log_debug

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

# Libfuse configuration
libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 120
 
# Disk cache related configuration
file_cache:
  path: /tmp/blob
  timeout-sec: 120
  max-eviction: 5000

# Attribute cache related configuration
attr_cache:
  timeout-sec: 120
  
# Azure storage configuration
azstorage:
  type: block
  account-name: <account>
  container: democentos
  endpoint: https://<account>.blob.region.domail.name/
  mode: key
  account-key: "*********"
```

I have kept log level as log_debug in this config, if it starts working you can just remove that line and it will be set to log_warning by default.
