### ISSUE TITLE
Unable to alter existing objects in block blob storage

### ISSUE THREAD

**Issue by mwestergaard** [Azure/azure-storage-fuse#948]
### Which version of blobfuse was used?
blobfuse2 version 2.0.0-preview.3

### Which OS distribution and version are you using?
Ubuntu 20.04.5 and Ubuntu 22.04.1

### If relevant, please share your mount command.
blobfuse2 mount /home/azureuser/blobfuse/ekmw --config-file=/home/azureuser/blobfuse/ekmw.yaml

### What was the issue encountered?
I mount a block blob storage container (flat namespace). I can't alter any existing object. I can create a new object but can't alter it (other than delete). For example:
```
$ touch a
$ echo "hello" > a
-bash: a: Invalid argument
$ touch b
$ cp a b
cp: cannot create regular file 'b': Invalid argument
$ ls -l
total 0
-rwxr-xr-x 1 azureuser azureuser 0 Oct 19 20:28 a
-rwxr-xr-x 1 azureuser azureuser 0 Oct 19 20:28 b
$ rm a b
$ ls -l
total 0
```
My config file looks like:

```
logging:
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

file_cache:
  path: /mnt/blobfusecache

azstorage:
  type: block
  account-name: <_account_>
  container: test
  endpoint: https://<_account_>.blob.core.windows.net
  mode: key
  account-key: <_key_>
```

### Have you found a mitigation/solution?
It works if I switch to an ADLS account (hierarchical namespace) account and change "type: adls".

### Please share logs if available.
No log was created, unless I am missing something. $HOME/.blobfuse2 contained only the pid file.
